-- JoomLeague 6.2 canonical MariaDB/MySQL foundation schema.

CREATE TABLE IF NOT EXISTS `#__joomleague_sport_profile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `name_key` VARCHAR(255) NOT NULL,
  `description_key` VARCHAR(255) NOT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_sport_profile_code` (`code`),
  KEY `idx_jl_sport_profile_published` (`published`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_sport_profile_version` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT UNSIGNED NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `profile_version` VARCHAR(50) NOT NULL,
  `payload_json` LONGTEXT NOT NULL,
  `payload_checksum` CHAR(64) NOT NULL,
  `source` VARCHAR(50) NOT NULL DEFAULT 'bundled',
  `state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_profile_version` (`profile_id`, `profile_version`),
  UNIQUE KEY `uq_jl_profile_payload` (`profile_id`, `payload_checksum`),
  KEY `idx_jl_profile_version_state` (`state`),
  CONSTRAINT `fk_jl_profile_version_profile`
    FOREIGN KEY (`profile_id`) REFERENCES `#__joomleague_sport_profile` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_sport_type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_version_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `overrides_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_sport_type_code` (`code`),
  UNIQUE KEY `uq_jl_sport_type_profile_binding` (`id`, `profile_version_id`),
  KEY `idx_jl_sport_type_profile` (`profile_version_id`),
  KEY `idx_jl_sport_type_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_sport_type_profile_version`
    FOREIGN KEY (`profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`)
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_sport_position` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `sport_type_id` BIGINT UNSIGNED NOT NULL, `source_profile_version_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `code` VARCHAR(100) NOT NULL, `name` VARCHAR(255) NOT NULL DEFAULT '', `name_key` VARCHAR(255) NULL DEFAULT NULL,
  `person_type` VARCHAR(100) NOT NULL, `lineup_group` VARCHAR(100) NULL DEFAULT NULL,
  `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL, `has_events` TINYINT NULL DEFAULT NULL, `has_statistics` TINYINT NULL DEFAULT NULL,
  `source` VARCHAR(30) NOT NULL DEFAULT 'local', `source_checksum` CHAR(64) NULL DEFAULT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL, `checked_out_time` DATETIME NULL DEFAULT NULL, `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_sport_position_uuid` (`uuid`), UNIQUE KEY `uq_jl_sport_position_code` (`sport_type_id`, `code`), UNIQUE KEY `uq_jl_sport_position_owner` (`id`, `sport_type_id`),
  KEY `idx_jl_sport_position_parent` (`parent_id`), KEY `idx_jl_sport_position_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_sport_position_type` FOREIGN KEY (`sport_type_id`) REFERENCES `#__joomleague_sport_type` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_sport_position_profile` FOREIGN KEY (`source_profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_sport_position_parent` FOREIGN KEY (`parent_id`) REFERENCES `#__joomleague_sport_position` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_event_type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `sport_type_id` BIGINT UNSIGNED NOT NULL, `source_profile_version_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `code` VARCHAR(100) NOT NULL, `name` VARCHAR(255) NOT NULL DEFAULT '', `name_key` VARCHAR(255) NULL DEFAULT NULL,
  `person_type` VARCHAR(100) NULL DEFAULT NULL, `timeline` TINYINT NOT NULL DEFAULT 0, `direction` SMALLINT NOT NULL DEFAULT 0,
  `affects_score` TINYINT NOT NULL DEFAULT 0, `score_delta` DECIMAL(12,4) NULL DEFAULT NULL, `score_target` VARCHAR(30) NULL DEFAULT NULL,
  `requires_second_person` TINYINT NOT NULL DEFAULT 0, `leads_to_suspension` TINYINT NOT NULL DEFAULT 0, `system_event` TINYINT NOT NULL DEFAULT 0,
  `source` VARCHAR(30) NOT NULL DEFAULT 'local', `source_checksum` CHAR(64) NULL DEFAULT NULL, `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL, `checked_out_time` DATETIME NULL DEFAULT NULL, `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_event_type_uuid` (`uuid`), UNIQUE KEY `uq_jl_event_type_code` (`sport_type_id`, `code`), UNIQUE KEY `uq_jl_event_type_owner` (`id`, `sport_type_id`),
  KEY `idx_jl_event_type_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_event_type_sport_type` FOREIGN KEY (`sport_type_id`) REFERENCES `#__joomleague_sport_type` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_event_type_profile` FOREIGN KEY (`source_profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_statistic` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `sport_type_id` BIGINT UNSIGNED NOT NULL, `source_profile_version_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `code` VARCHAR(100) NOT NULL, `name` VARCHAR(255) NOT NULL DEFAULT '', `name_key` VARCHAR(255) NULL DEFAULT NULL,
  `abbreviation_key` VARCHAR(255) NULL DEFAULT NULL, `statistic_type` VARCHAR(100) NOT NULL DEFAULT 'basic',
  `scope` VARCHAR(100) NOT NULL, `value_type` VARCHAR(100) NOT NULL DEFAULT 'integer', `calculation_source` VARCHAR(100) NOT NULL DEFAULT 'manual',
  `source` VARCHAR(30) NOT NULL DEFAULT 'local', `source_checksum` CHAR(64) NULL DEFAULT NULL, `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL, `checked_out_time` DATETIME NULL DEFAULT NULL, `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_statistic_uuid` (`uuid`), UNIQUE KEY `uq_jl_statistic_code` (`sport_type_id`, `code`), UNIQUE KEY `uq_jl_statistic_owner` (`id`, `sport_type_id`),
  KEY `idx_jl_statistic_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_statistic_sport_type` FOREIGN KEY (`sport_type_id`) REFERENCES `#__joomleague_sport_type` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_statistic_profile` FOREIGN KEY (`source_profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_position_event_type` (
  `position_id` BIGINT UNSIGNED NOT NULL, `event_type_id` BIGINT UNSIGNED NOT NULL, `sport_type_id` BIGINT UNSIGNED NOT NULL,
  `ordering` INT NOT NULL DEFAULT 0, `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`position_id`, `event_type_id`), KEY `idx_jl_position_event_type_event` (`event_type_id`, `sport_type_id`),
  CONSTRAINT `fk_jl_position_event_position` FOREIGN KEY (`position_id`, `sport_type_id`) REFERENCES `#__joomleague_sport_position` (`id`, `sport_type_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_position_event_event` FOREIGN KEY (`event_type_id`, `sport_type_id`) REFERENCES `#__joomleague_event_type` (`id`, `sport_type_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_position_statistic` (
  `position_id` BIGINT UNSIGNED NOT NULL, `statistic_id` BIGINT UNSIGNED NOT NULL, `sport_type_id` BIGINT UNSIGNED NOT NULL,
  `ordering` INT NOT NULL DEFAULT 0, `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`position_id`, `statistic_id`), KEY `idx_jl_position_statistic_stat` (`statistic_id`, `sport_type_id`),
  CONSTRAINT `fk_jl_position_stat_position` FOREIGN KEY (`position_id`, `sport_type_id`) REFERENCES `#__joomleague_sport_position` (`id`, `sport_type_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_position_stat_stat` FOREIGN KEY (`statistic_id`, `sport_type_id`) REFERENCES `#__joomleague_statistic` (`id`, `sport_type_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_profile_template_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_version_id` BIGINT UNSIGNED NOT NULL,
  `template_code` VARCHAR(100) NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `params_json` LONGTEXT NOT NULL,
  `params_checksum` CHAR(64) NOT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_profile_template` (`profile_version_id`, `template_code`),
  KEY `idx_jl_profile_template_state` (`published`),
  CONSTRAINT `fk_jl_profile_template_version`
    FOREIGN KEY (`profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_competition` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(100) NOT NULL DEFAULT '',
  `short_name` VARCHAR(50) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `organisation` VARCHAR(255) NULL DEFAULT NULL,
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_competition_uuid` (`uuid`),
  KEY `idx_jl_competition_code` (`code`),
  KEY `idx_jl_competition_state` (`published`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_season` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_season_uuid` (`uuid`),
  KEY `idx_jl_season_dates` (`start_date`, `end_date`),
  KEY `idx_jl_season_state` (`published`, `ordering`),
  CONSTRAINT `chk_jl_season_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `competition_id` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL,
  `sport_type_id` BIGINT UNSIGNED NOT NULL,
  `profile_version_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `project_type` VARCHAR(100) NOT NULL,
  `timezone` VARCHAR(100) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `default_start_time` VARCHAR(5) NULL DEFAULT NULL,
  `current_round_mode` VARCHAR(30) NOT NULL DEFAULT 'start',
  `auto_advance_seconds` INT UNSIGNED NULL DEFAULT 7200,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'draft',
  `description` TEXT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 0,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_uuid` (`uuid`),
  KEY `idx_jl_project_competition` (`competition_id`),
  KEY `idx_jl_project_season` (`season_id`),
  KEY `idx_jl_project_profile` (`profile_version_id`),
  KEY `idx_jl_project_state` (`published`, `lifecycle_state`, `ordering`),
  KEY `idx_jl_project_schedule` (`start_date`, `end_date`),
  CONSTRAINT `fk_jl_project_competition`
    FOREIGN KEY (`competition_id`) REFERENCES `#__joomleague_competition` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_season`
    FOREIGN KEY (`season_id`) REFERENCES `#__joomleague_season` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_sport_binding`
    FOREIGN KEY (`sport_type_id`, `profile_version_id`)
    REFERENCES `#__joomleague_sport_type` (`id`, `profile_version_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_project_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`),
  CONSTRAINT `chk_jl_project_auto_advance` CHECK (`auto_advance_seconds` IS NULL OR `auto_advance_seconds` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_stage` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NOT NULL,
  `stage_type` VARCHAR(100) NOT NULL,
  `entry_selection_mode` VARCHAR(30) NOT NULL DEFAULT 'inherit_project',
  `sequence_number` INT UNSIGNED NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 0,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_stage_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_project_stage_code` (`project_id`, `code`),
  UNIQUE KEY `uq_jl_project_stage_owner` (`id`, `project_id`),
  KEY `idx_jl_project_stage_parent` (`parent_id`),
  KEY `idx_jl_project_stage_state` (`project_id`, `published`, `ordering`),
  KEY `idx_jl_project_stage_dates` (`start_date`, `end_date`),
  CONSTRAINT `fk_jl_project_stage_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_stage_parent` FOREIGN KEY (`parent_id`) REFERENCES `#__joomleague_project_stage` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_project_stage_entry_mode` CHECK (`entry_selection_mode` IN ('inherit_project', 'explicit')),
  CONSTRAINT `chk_jl_project_stage_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_round` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `stage_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NOT NULL,
  `round_type` VARCHAR(100) NOT NULL DEFAULT 'standard',
  `sequence_number` INT UNSIGNED NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'draft',
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 0,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_round_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_project_round_code` (`stage_id`, `code`),
  UNIQUE KEY `uq_jl_project_round_sequence` (`stage_id`, `sequence_number`),
  UNIQUE KEY `uq_jl_project_round_owner` (`id`, `project_id`),
  UNIQUE KEY `uq_jl_project_round_scope` (`id`, `stage_id`, `project_id`),
  KEY `idx_jl_project_round_state` (`project_id`, `stage_id`, `published`, `ordering`),
  KEY `idx_jl_project_round_dates` (`start_date`, `end_date`),
  CONSTRAINT `fk_jl_project_round_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_round_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_project_round_sequence` CHECK (`sequence_number` > 0),
  CONSTRAINT `chk_jl_project_round_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_rule_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `overrides_json` LONGTEXT NOT NULL,
  `overrides_checksum` CHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_rule_config` (`project_id`),
  CONSTRAINT `fk_jl_project_rule_config_project`
    FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_template_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `template_code` VARCHAR(100) NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `params_json` LONGTEXT NOT NULL,
  `params_checksum` CHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_template_config` (`project_id`, `template_code`),
  KEY `idx_jl_project_template_code` (`template_code`),
  CONSTRAINT `fk_jl_project_template_project`
    FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_club` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `founded_date` DATE NULL DEFAULT NULL,
  `dissolved_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_club_uuid` (`uuid`),
  KEY `idx_jl_club_state` (`published`, `ordering`),
  CONSTRAINT `chk_jl_club_dates` CHECK (`dissolved_date` IS NULL OR `founded_date` IS NULL OR `dissolved_date` >= `founded_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_venue` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `owner_club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nickname` VARCHAR(100) NOT NULL DEFAULT '',
  `address` VARCHAR(255) NOT NULL DEFAULT '',
  `postal_code` VARCHAR(20) NOT NULL DEFAULT '',
  `city` VARCHAR(100) NOT NULL DEFAULT '',
  `region` VARCHAR(100) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `timezone` VARCHAR(64) NULL DEFAULT NULL,
  `capacity` BIGINT UNSIGNED NULL DEFAULT NULL,
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_venue_uuid` (`uuid`),
  KEY `idx_jl_venue_owner_club` (`owner_club_id`),
  KEY `idx_jl_venue_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_venue_owner_club` FOREIGN KEY (`owner_club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_venue_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
  CONSTRAINT `chk_jl_venue_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_team` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(100) NOT NULL DEFAULT '',
  `short_name` VARCHAR(50) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_team_uuid` (`uuid`),
  KEY `idx_jl_team_club` (`club_id`),
  KEY `idx_jl_team_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_team_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_organization_name_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_to` DATE NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_org_name_history_uuid` (`uuid`),
  KEY `idx_jl_org_name_history_club` (`club_id`, `valid_from`, `ordering`),
  KEY `idx_jl_org_name_history_team` (`team_id`, `valid_from`, `ordering`),
  CONSTRAINT `fk_jl_org_name_history_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_org_name_history_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_org_name_history_owner` CHECK ((`club_id` IS NOT NULL AND `team_id` IS NULL) OR (`club_id` IS NULL AND `team_id` IS NOT NULL)),
  CONSTRAINT `chk_jl_org_name_history_dates` CHECK (`valid_to` IS NULL OR `valid_from` IS NULL OR `valid_to` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_organization_media_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `media_type` VARCHAR(100) NOT NULL DEFAULT 'logo',
  `media_path` VARCHAR(255) NOT NULL,
  `alt_text` VARCHAR(255) NOT NULL DEFAULT '',
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_to` DATE NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_org_media_history_uuid` (`uuid`),
  KEY `idx_jl_org_media_history_club` (`club_id`, `media_type`, `valid_from`, `ordering`),
  KEY `idx_jl_org_media_history_team` (`team_id`, `media_type`, `valid_from`, `ordering`),
  CONSTRAINT `fk_jl_org_media_history_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_org_media_history_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_org_media_history_owner` CHECK ((`club_id` IS NOT NULL AND `team_id` IS NULL) OR (`club_id` IS NULL AND `team_id` IS NOT NULL)),
  CONSTRAINT `chk_jl_org_media_history_dates` CHECK (`valid_to` IS NULL OR `valid_from` IS NULL OR `valid_to` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_person` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `contact_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NOT NULL DEFAULT '',
  `last_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nickname` VARCHAR(100) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `death_date` DATE NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_person_uuid` (`uuid`),
  KEY `idx_jl_person_name` (`last_name`, `first_name`),
  KEY `idx_jl_person_state` (`published`, `ordering`),
  KEY `idx_jl_person_club` (`club_id`),
  CONSTRAINT `chk_jl_person_dates` CHECK (`death_date` IS NULL OR `birth_date` IS NULL OR `death_date` >= `birth_date`),
  CONSTRAINT `fk_jl_person_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_entry` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `entry_kind` VARCHAR(20) NOT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `display_name` VARCHAR(255) NOT NULL DEFAULT '',
  `entry_code` VARCHAR(100) NULL DEFAULT NULL,
  `seed_number` INT UNSIGNED NULL DEFAULT NULL,
  `bib_number` VARCHAR(50) NULL DEFAULT NULL,
  `included_in_standings` TINYINT NOT NULL DEFAULT 1,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_entry_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_project_entry_team` (`project_id`, `team_id`),
  UNIQUE KEY `uq_jl_project_entry_person` (`project_id`, `person_id`),
  UNIQUE KEY `uq_jl_project_entry_owner` (`id`, `project_id`),
  KEY `idx_jl_project_entry_state` (`project_id`, `published`, `ordering`),
  CONSTRAINT `fk_jl_project_entry_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_entry_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_entry_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_project_entry_kind` CHECK (`entry_kind` IN ('team', 'person', 'group')),
  CONSTRAINT `chk_jl_project_entry_target` CHECK ((`entry_kind` = 'team' AND `team_id` IS NOT NULL AND `person_id` IS NULL) OR (`entry_kind` = 'person' AND `person_id` IS NOT NULL AND `team_id` IS NULL) OR (`entry_kind` = 'group' AND `team_id` IS NULL AND `person_id` IS NULL AND `display_name` <> ''))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_stage_entry` (
  `stage_id` BIGINT UNSIGNED NOT NULL,
  `entry_id` BIGINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `seed_number` INT UNSIGNED NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `manual_assignment` TINYINT NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`stage_id`, `entry_id`),
  KEY `idx_jl_stage_entry_entry` (`entry_id`, `project_id`),
  CONSTRAINT `fk_jl_stage_entry_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_entry_entry` FOREIGN KEY (`entry_id`, `project_id`) REFERENCES `#__joomleague_project_entry` (`id`, `project_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_match` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL, `stage_id` BIGINT UNSIGNED NOT NULL, `round_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(100) NULL DEFAULT NULL, `match_number` VARCHAR(100) NULL DEFAULT NULL, `contest_type` VARCHAR(100) NOT NULL DEFAULT 'head_to_head',
  `scheduled_start` DATETIME NULL DEFAULT NULL, `timezone` VARCHAR(100) NULL DEFAULT NULL, `duration_minutes` INT UNSIGNED NULL DEFAULT NULL,
  `venue_id` BIGINT UNSIGNED NULL DEFAULT NULL, `attendance` BIGINT UNSIGNED NULL DEFAULT NULL, `status_code` VARCHAR(100) NOT NULL DEFAULT 'scheduled',
  `description` TEXT NULL, `metadata_json` LONGTEXT NULL, `published` TINYINT NOT NULL DEFAULT 0, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL, `checked_out_time` DATETIME NULL DEFAULT NULL, `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_project_match_uuid` (`uuid`), UNIQUE KEY `uq_jl_project_match_code` (`round_id`, `code`),
  UNIQUE KEY `uq_jl_project_match_owner` (`id`, `project_id`), KEY `idx_jl_project_match_schedule` (`project_id`, `scheduled_start`),
  KEY `idx_jl_project_match_round` (`round_id`, `status_code`, `ordering`), KEY `idx_jl_project_match_venue` (`venue_id`),
  CONSTRAINT `fk_jl_project_match_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_match_round` FOREIGN KEY (`round_id`, `stage_id`, `project_id`) REFERENCES `#__joomleague_project_round` (`id`, `stage_id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_match_venue` FOREIGN KEY (`venue_id`) REFERENCES `#__joomleague_venue` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_participant` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL, `project_entry_id` BIGINT UNSIGNED NOT NULL, `role_code` VARCHAR(100) NOT NULL DEFAULT 'participant',
  `slot_number` INT UNSIGNED NOT NULL, `participation_status` VARCHAR(100) NULL DEFAULT NULL,
  `result_status` VARCHAR(100) NOT NULL DEFAULT 'scheduled', `result_rank` INT UNSIGNED NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL, `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_participant_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_participant_entry` (`match_id`, `project_entry_id`),
  UNIQUE KEY `uq_jl_match_participant_slot` (`match_id`, `slot_number`), UNIQUE KEY `uq_jl_match_participant_scope` (`id`, `match_id`), KEY `idx_jl_match_participant_entry` (`project_entry_id`, `project_id`),
  CONSTRAINT `fk_jl_match_participant_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_participant_entry` FOREIGN KEY (`project_entry_id`, `project_id`) REFERENCES `#__joomleague_project_entry` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_match_participant_slot` CHECK (`slot_number` > 0),
  CONSTRAINT `chk_jl_match_participant_rank` CHECK (`result_rank` IS NULL OR `result_rank` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_result` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL,
  `result_type` VARCHAR(100) NOT NULL, `status_code` VARCHAR(100) NOT NULL DEFAULT 'draft', `outcome_code` VARCHAR(100) NULL DEFAULT NULL,
  `finalized_at` DATETIME NULL DEFAULT NULL, `notes` TEXT NULL, `metadata_json` LONGTEXT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_result_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_result_match` (`match_id`),
  CONSTRAINT `fk_jl_match_result_match` FOREIGN KEY (`match_id`) REFERENCES `#__joomleague_project_match` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_score_segment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL, `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `level_code` VARCHAR(100) NOT NULL, `segment_type_ordinal` INT UNSIGNED NOT NULL DEFAULT 0, `sequence_number` INT UNSIGNED NOT NULL,
  `root_marker` TINYINT GENERATED ALWAYS AS (CASE WHEN `parent_id` IS NULL THEN 0 ELSE NULL END) STORED,
  `status_code` VARCHAR(100) NOT NULL DEFAULT 'completed',
  `metadata_json` LONGTEXT NULL, `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_score_segment_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_score_segment_root` (`match_id`, `root_marker`),
  UNIQUE KEY `uq_jl_match_score_segment_position` (`match_id`, `parent_id`, `level_code`, `sequence_number`),
  UNIQUE KEY `uq_jl_match_score_segment_scope` (`id`, `match_id`), KEY `idx_jl_match_score_segment_parent` (`parent_id`, `match_id`),
  CONSTRAINT `fk_jl_match_score_segment_match` FOREIGN KEY (`match_id`) REFERENCES `#__joomleague_project_match` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_score_segment_parent` FOREIGN KEY (`parent_id`, `match_id`) REFERENCES `#__joomleague_match_score_segment` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_match_score_segment_sequence` CHECK (`sequence_number` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_score_value` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL, `segment_id` BIGINT UNSIGNED NOT NULL, `participant_id` BIGINT UNSIGNED NOT NULL,
  `numeric_value` DECIMAL(30,9) NULL DEFAULT NULL, `text_value` VARCHAR(255) NULL DEFAULT NULL, `status_code` VARCHAR(100) NULL DEFAULT NULL, `result_rank` INT UNSIGNED NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL, `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_score_value_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_score_value_participant` (`segment_id`, `participant_id`),
  KEY `idx_jl_match_score_value_match` (`match_id`, `result_rank`), KEY `idx_jl_match_score_value_participant` (`participant_id`, `match_id`),
  CONSTRAINT `fk_jl_match_score_value_segment` FOREIGN KEY (`segment_id`, `match_id`) REFERENCES `#__joomleague_match_score_segment` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_score_value_participant` FOREIGN KEY (`participant_id`, `match_id`) REFERENCES `#__joomleague_match_participant` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_match_score_value_rank` CHECK (`result_rank` IS NULL OR `result_rank` > 0),
  CONSTRAINT `chk_jl_match_score_value_payload` CHECK (`numeric_value` IS NOT NULL OR `text_value` IS NOT NULL OR `status_code` IS NOT NULL OR `result_rank` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_entry_member` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `entry_id` BIGINT UNSIGNED NOT NULL,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `member_person_type` VARCHAR(50) NOT NULL,
  `role_code` VARCHAR(100) NULL DEFAULT NULL,
  `shirt_number` VARCHAR(20) NULL DEFAULT NULL,
  `is_captain` TINYINT NOT NULL DEFAULT 0,
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_until` DATE NULL DEFAULT NULL,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_entry_member_uuid` (`uuid`),
  KEY `idx_jl_entry_member_entry` (`entry_id`, `published`, `ordering`),
  KEY `idx_jl_entry_member_person` (`person_id`, `valid_from`, `valid_until`),
  CONSTRAINT `fk_jl_entry_member_entry` FOREIGN KEY (`entry_id`) REFERENCES `#__joomleague_project_entry` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_entry_member_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_entry_member_dates` CHECK (`valid_until` IS NULL OR `valid_from` IS NULL OR `valid_until` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_lineup_member` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `match_id` BIGINT UNSIGNED NOT NULL,
  `match_participant_id` BIGINT UNSIGNED NOT NULL,
  `source_entry_member_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `member_person_type` VARCHAR(50) NOT NULL,
  `role_code` VARCHAR(100) NULL DEFAULT NULL,
  `shirt_number` VARCHAR(20) NULL DEFAULT NULL,
  `lineup_status` VARCHAR(50) NOT NULL DEFAULT 'available',
  `is_captain` TINYINT NOT NULL DEFAULT 0,
  `notes` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_match_lineup_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_match_lineup_person` (`match_participant_id`, `person_id`),
  UNIQUE KEY `uq_jl_match_lineup_scope` (`id`, `match_id`, `match_participant_id`),
  KEY `idx_jl_match_lineup_match` (`match_id`, `match_participant_id`, `member_person_type`, `ordering`),
  KEY `idx_jl_match_lineup_source` (`source_entry_member_id`),
  CONSTRAINT `fk_jl_match_lineup_participant` FOREIGN KEY (`match_participant_id`, `match_id`) REFERENCES `#__joomleague_match_participant` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_lineup_source` FOREIGN KEY (`source_entry_member_id`) REFERENCES `#__joomleague_project_entry_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_lineup_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_lineup_change` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `match_id` BIGINT UNSIGNED NOT NULL, `match_participant_id` BIGINT UNSIGNED NOT NULL,
  `outgoing_lineup_member_id` BIGINT UNSIGNED NOT NULL, `incoming_lineup_member_id` BIGINT UNSIGNED NOT NULL,
  `change_type` VARCHAR(50) NOT NULL DEFAULT 'substitution', `sequence_number` INT UNSIGNED NOT NULL,
  `phase_code` VARCHAR(100) NULL DEFAULT NULL, `phase_sequence` INT UNSIGNED NULL DEFAULT NULL,
  `clock_value` DECIMAL(30,9) NULL DEFAULT NULL, `clock_unit` VARCHAR(50) NULL DEFAULT NULL,
  `notes` TEXT NULL, `metadata_json` LONGTEXT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_lineup_change_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_match_lineup_change_sequence` (`match_participant_id`, `sequence_number`),
  KEY `idx_jl_match_lineup_change_match` (`match_id`, `match_participant_id`, `sequence_number`),
  CONSTRAINT `fk_jl_lineup_change_outgoing` FOREIGN KEY (`outgoing_lineup_member_id`, `match_id`, `match_participant_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`, `match_id`, `match_participant_id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_lineup_change_incoming` FOREIGN KEY (`incoming_lineup_member_id`, `match_id`, `match_participant_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`, `match_id`, `match_participant_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_lineup_change_members` CHECK (`outgoing_lineup_member_id` <> `incoming_lineup_member_id`),
  CONSTRAINT `chk_jl_lineup_change_sequence` CHECK (`sequence_number` > 0),
  CONSTRAINT `chk_jl_lineup_change_phase` CHECK (`phase_sequence` IS NULL OR `phase_sequence` > 0),
  CONSTRAINT `chk_jl_lineup_change_clock` CHECK (`clock_value` IS NULL OR `clock_value` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_actor_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL,
  `actor_kind` VARCHAR(20) NOT NULL, `person_id` BIGINT UNSIGNED NULL DEFAULT NULL, `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `role_code` VARCHAR(100) NOT NULL, `person_type` VARCHAR(100) NOT NULL,
  `valid_from` DATE NULL DEFAULT NULL, `valid_until` DATE NULL DEFAULT NULL, `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL, `metadata_json` LONGTEXT NULL, `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_project_actor_role_uuid` (`uuid`),
  KEY `idx_jl_project_actor_role_project` (`project_id`, `person_type`, `published`, `ordering`),
  KEY `idx_jl_project_actor_role_person` (`person_id`, `valid_from`, `valid_until`),
  KEY `idx_jl_project_actor_role_team` (`team_id`, `valid_from`, `valid_until`),
  CONSTRAINT `fk_jl_project_actor_role_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_actor_role_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_actor_role_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_project_actor_role_actor` CHECK ((`actor_kind` = 'person' AND `person_id` IS NOT NULL AND `team_id` IS NULL) OR (`actor_kind` = 'team' AND `team_id` IS NOT NULL AND `person_id` IS NULL)),
  CONSTRAINT `chk_jl_project_actor_role_dates` CHECK (`valid_until` IS NULL OR `valid_from` IS NULL OR `valid_until` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_actor_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL,
  `source_project_actor_role_id` BIGINT UNSIGNED NULL DEFAULT NULL, `actor_kind` VARCHAR(20) NOT NULL,
  `person_id` BIGINT UNSIGNED NULL DEFAULT NULL, `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `role_code` VARCHAR(100) NOT NULL, `person_type` VARCHAR(100) NOT NULL, `display_name_snapshot` VARCHAR(255) NOT NULL,
  `notes` TEXT NULL, `metadata_json` LONGTEXT NULL, `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_actor_role_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_match_actor_role_source` (`match_id`, `source_project_actor_role_id`),
  KEY `idx_jl_match_actor_role_match` (`match_id`, `person_type`, `ordering`), KEY `idx_jl_match_actor_role_project` (`project_id`),
  KEY `idx_jl_match_actor_role_person` (`person_id`), KEY `idx_jl_match_actor_role_team` (`team_id`),
  CONSTRAINT `fk_jl_match_actor_role_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_actor_role_source` FOREIGN KEY (`source_project_actor_role_id`) REFERENCES `#__joomleague_project_actor_role` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_actor_role_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_actor_role_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_match_actor_role_actor` CHECK ((`actor_kind` = 'person' AND `person_id` IS NOT NULL AND `team_id` IS NULL) OR (`actor_kind` = 'team' AND `team_id` IS NOT NULL AND `person_id` IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `match_id` BIGINT UNSIGNED NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL,
  `match_participant_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `source_event_type_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `event_code` VARCHAR(100) NOT NULL, `event_name_key` VARCHAR(255) NOT NULL,
  `event_person_type` VARCHAR(100) NULL DEFAULT NULL, `sequence_number` INT UNSIGNED NOT NULL,
  `primary_lineup_member_id` BIGINT UNSIGNED NULL DEFAULT NULL, `primary_person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `primary_name_snapshot` VARCHAR(255) NULL DEFAULT NULL,
  `secondary_lineup_member_id` BIGINT UNSIGNED NULL DEFAULT NULL, `secondary_person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `secondary_name_snapshot` VARCHAR(255) NULL DEFAULT NULL,
  `source_match_actor_role_id` BIGINT UNSIGNED NULL DEFAULT NULL, `actor_name_snapshot` VARCHAR(255) NULL DEFAULT NULL,
  `score_segment_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `phase_code` VARCHAR(100) NULL DEFAULT NULL, `phase_sequence` INT UNSIGNED NULL DEFAULT NULL,
  `clock_value` DECIMAL(30,9) NULL DEFAULT NULL, `clock_unit` VARCHAR(50) NULL DEFAULT NULL,
  `occurred_at` DATETIME NULL DEFAULT NULL, `numeric_value` DECIMAL(30,9) NULL DEFAULT NULL, `text_value` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL, `profile_metadata_json` LONGTEXT NOT NULL, `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_event_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_event_sequence` (`match_id`, `sequence_number`),
  KEY `idx_jl_match_event_timeline` (`match_id`, `phase_code`, `phase_sequence`, `clock_value`, `sequence_number`),
  KEY `idx_jl_match_event_participant` (`match_participant_id`, `event_code`), KEY `idx_jl_match_event_primary_person` (`primary_person_id`),
  KEY `idx_jl_match_event_secondary_person` (`secondary_person_id`), KEY `idx_jl_match_event_actor` (`source_match_actor_role_id`),
  CONSTRAINT `fk_jl_match_event_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_event_participant` FOREIGN KEY (`match_participant_id`, `match_id`) REFERENCES `#__joomleague_match_participant` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_event_catalog` FOREIGN KEY (`source_event_type_id`) REFERENCES `#__joomleague_event_type` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_primary_lineup` FOREIGN KEY (`primary_lineup_member_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_primary_person` FOREIGN KEY (`primary_person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_event_secondary_lineup` FOREIGN KEY (`secondary_lineup_member_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_secondary_person` FOREIGN KEY (`secondary_person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_event_actor` FOREIGN KEY (`source_match_actor_role_id`) REFERENCES `#__joomleague_match_actor_role` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_segment` FOREIGN KEY (`score_segment_id`) REFERENCES `#__joomleague_match_score_segment` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_match_event_sequence` CHECK (`sequence_number` > 0),
  CONSTRAINT `chk_jl_match_event_phase` CHECK (`phase_sequence` IS NULL OR `phase_sequence` > 0),
  CONSTRAINT `chk_jl_match_event_clock` CHECK (`clock_value` IS NULL OR `clock_value` >= 0),
  CONSTRAINT `chk_jl_match_event_primary_snapshot` CHECK ((`primary_person_id` IS NULL AND `primary_name_snapshot` IS NULL) OR (`primary_person_id` IS NOT NULL AND `primary_name_snapshot` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_event_secondary_snapshot` CHECK ((`secondary_person_id` IS NULL AND `secondary_name_snapshot` IS NULL) OR (`secondary_person_id` IS NOT NULL AND `secondary_name_snapshot` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_event_people` CHECK (`secondary_person_id` IS NULL OR (`primary_person_id` IS NOT NULL AND `secondary_person_id` <> `primary_person_id`)),
  CONSTRAINT `chk_jl_match_event_clock_unit` CHECK ((`clock_value` IS NULL AND `clock_unit` IS NULL) OR (`clock_value` IS NOT NULL AND `clock_unit` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_match_statistic_value` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `match_id` BIGINT UNSIGNED NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL,
  `source_statistic_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `statistic_code` VARCHAR(100) NOT NULL, `statistic_name_key` VARCHAR(255) NOT NULL, `abbreviation_key` VARCHAR(255) NULL DEFAULT NULL,
  `statistic_type` VARCHAR(100) NOT NULL, `scope_code` VARCHAR(100) NOT NULL, `value_type` VARCHAR(100) NOT NULL,
  `calculation_source` VARCHAR(100) NOT NULL, `target_kind` VARCHAR(20) NOT NULL,
  `match_participant_id` BIGINT UNSIGNED NOT NULL, `lineup_member_id` BIGINT UNSIGNED NULL DEFAULT NULL, `person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `target_key` VARCHAR(191) NOT NULL, `target_name_snapshot` VARCHAR(255) NOT NULL,
  `score_segment_id` BIGINT UNSIGNED NULL DEFAULT NULL, `segment_key` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `segment_code_snapshot` VARCHAR(100) NULL DEFAULT NULL, `segment_sequence_snapshot` INT UNSIGNED NULL DEFAULT NULL,
  `numeric_value` DECIMAL(30,9) NULL DEFAULT NULL, `text_value` VARCHAR(1000) NULL DEFAULT NULL,
  `notes` TEXT NULL, `profile_metadata_json` LONGTEXT NOT NULL, `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_stat_value_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_match_stat_value_target` (`match_id`, `statistic_code`, `target_key`, `segment_key`),
  KEY `idx_jl_match_stat_value_match` (`match_id`, `scope_code`, `statistic_code`), KEY `idx_jl_match_stat_value_participant` (`match_participant_id`),
  KEY `idx_jl_match_stat_value_person` (`person_id`), KEY `idx_jl_match_stat_value_catalog` (`source_statistic_id`),
  CONSTRAINT `fk_jl_match_stat_value_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_stat_value_participant` FOREIGN KEY (`match_participant_id`, `match_id`) REFERENCES `#__joomleague_match_participant` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_stat_value_catalog` FOREIGN KEY (`source_statistic_id`) REFERENCES `#__joomleague_statistic` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_stat_value_lineup` FOREIGN KEY (`lineup_member_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_stat_value_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_stat_value_segment` FOREIGN KEY (`score_segment_id`) REFERENCES `#__joomleague_match_score_segment` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_match_stat_value_target` CHECK ((`target_kind` = 'participant' AND `person_id` IS NULL) OR (`target_kind` = 'person' AND `person_id` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_stat_value_payload` CHECK ((`numeric_value` IS NOT NULL AND `text_value` IS NULL) OR (`numeric_value` IS NULL AND `text_value` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_stat_value_segment` CHECK ((`segment_key` = 0 AND `segment_code_snapshot` IS NULL AND `segment_sequence_snapshot` IS NULL) OR (`segment_key` > 0 AND `segment_code_snapshot` IS NOT NULL AND `segment_sequence_snapshot` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_stat_value_segment_sequence` CHECK (`segment_sequence_snapshot` IS NULL OR `segment_sequence_snapshot` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_standing_adjustment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL, `stage_id` BIGINT UNSIGNED NULL DEFAULT NULL, `stage_key` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `project_entry_id` BIGINT UNSIGNED NOT NULL, `scope_code` VARCHAR(100) NOT NULL DEFAULT 'all', `metric_code` VARCHAR(100) NOT NULL,
  `adjustment_value` DECIMAL(30,9) NOT NULL, `reason` VARCHAR(500) NOT NULL, `effective_date` DATE NULL DEFAULT NULL,
  `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_standing_adjustment_uuid` (`uuid`),
  KEY `idx_jl_standing_adjustment_context` (`project_id`, `stage_key`, `scope_code`, `published`, `ordering`), KEY `idx_jl_standing_adjustment_entry` (`project_entry_id`),
  CONSTRAINT `fk_jl_standing_adjustment_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_adjustment_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_adjustment_entry` FOREIGN KEY (`project_entry_id`, `project_id`) REFERENCES `#__joomleague_project_entry` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_standing_adjustment_stage` CHECK ((`stage_id` IS NULL AND `stage_key` = 0) OR (`stage_id` IS NOT NULL AND `stage_key` = `stage_id`)),
  CONSTRAINT `chk_jl_standing_adjustment_scope` CHECK (`scope_code` REGEXP '^[a-z][a-z0-9_]*$'),
  CONSTRAINT `chk_jl_standing_adjustment_metric` CHECK (`metric_code` REGEXP '^[a-z][a-z0-9_]*$'),
  CONSTRAINT `chk_jl_standing_adjustment_value` CHECK (`adjustment_value` <> 0), CONSTRAINT `chk_jl_standing_adjustment_published` CHECK (`published` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_standing_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL, `stage_id` BIGINT UNSIGNED NULL DEFAULT NULL, `stage_key` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `scope_code` VARCHAR(100) NOT NULL, `standings_type` VARCHAR(100) NOT NULL, `profile_version_id` BIGINT UNSIGNED NOT NULL,
  `profile_checksum` CHAR(64) NOT NULL, `input_checksum` CHAR(64) NOT NULL, `contract_json` LONGTEXT NOT NULL,
  `row_count` INT UNSIGNED NOT NULL DEFAULT 0, `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `generated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_standing_snapshot_uuid` (`uuid`), UNIQUE KEY `uq_jl_standing_snapshot_input` (`project_id`, `stage_key`, `scope_code`, `input_checksum`),
  UNIQUE KEY `uq_jl_standing_snapshot_owner` (`id`, `project_id`), KEY `idx_jl_standing_snapshot_stage` (`stage_id`, `generated_at`),
  CONSTRAINT `fk_jl_standing_snapshot_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_snapshot_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_snapshot_profile` FOREIGN KEY (`profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_standing_snapshot_stage` CHECK ((`stage_id` IS NULL AND `stage_key` = 0) OR (`stage_id` IS NOT NULL AND `stage_key` = `stage_id`)),
  CONSTRAINT `chk_jl_standing_snapshot_rows` CHECK (`row_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_standing_snapshot_row` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `snapshot_id` BIGINT UNSIGNED NOT NULL, `project_entry_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `entry_id_snapshot` BIGINT UNSIGNED NOT NULL, `entry_name_snapshot` VARCHAR(255) NOT NULL, `rank_number` INT UNSIGNED NOT NULL,
  `sequence_number` INT UNSIGNED NOT NULL, `metrics_json` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_standing_row_entry` (`snapshot_id`, `entry_id_snapshot`), KEY `idx_jl_standing_row_order` (`snapshot_id`, `sequence_number`), KEY `idx_jl_standing_row_entry` (`project_entry_id`),
  CONSTRAINT `fk_jl_standing_row_snapshot` FOREIGN KEY (`snapshot_id`) REFERENCES `#__joomleague_standing_snapshot` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_row_entry` FOREIGN KEY (`project_entry_id`) REFERENCES `#__joomleague_project_entry` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_standing_row_rank` CHECK (`rank_number` > 0 AND `sequence_number` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_standing_current` (
  `project_id` BIGINT UNSIGNED NOT NULL, `stage_key` BIGINT UNSIGNED NOT NULL DEFAULT 0, `scope_code` VARCHAR(100) NOT NULL, `snapshot_id` BIGINT UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`project_id`, `stage_key`, `scope_code`), UNIQUE KEY `uq_jl_standing_current_snapshot` (`snapshot_id`),
  CONSTRAINT `fk_jl_standing_current_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_standing_current_snapshot` FOREIGN KEY (`snapshot_id`, `project_id`) REFERENCES `#__joomleague_standing_snapshot` (`id`, `project_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_stage_transition` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `source_stage_id` BIGINT UNSIGNED NOT NULL,
  `target_stage_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `selector_type` VARCHAR(100) NOT NULL,
  `selector_config_json` LONGTEXT NULL,
  `carry_over_mode` VARCHAR(100) NOT NULL DEFAULT 'none',
  `target_seed_start` INT UNSIGNED NULL DEFAULT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_stage_transition_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_stage_transition_code` (`project_id`, `code`),
  KEY `idx_jl_stage_transition_source` (`source_stage_id`, `project_id`, `published`, `ordering`),
  KEY `idx_jl_stage_transition_target` (`target_stage_id`, `project_id`),
  CONSTRAINT `fk_jl_stage_transition_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_source` FOREIGN KEY (`source_stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_target` FOREIGN KEY (`target_stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_stage_transition_distinct` CHECK (`source_stage_id` <> `target_stage_id`),
  CONSTRAINT `chk_jl_stage_transition_selector` CHECK (`selector_type` REGEXP '^[a-z][a-z0-9_]*$'),
  CONSTRAINT `chk_jl_stage_transition_carry` CHECK (`carry_over_mode` REGEXP '^[a-z][a-z0-9_]*$'),
  CONSTRAINT `chk_jl_stage_transition_seed` CHECK (`target_seed_start` IS NULL OR `target_seed_start` > 0),
  CONSTRAINT `chk_jl_stage_transition_published` CHECK (`published` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_stage_transition_run` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `transition_id` BIGINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `input_checksum` CHAR(64) NOT NULL,
  `selector_snapshot_json` LONGTEXT NOT NULL,
  `resolved_entries_json` LONGTEXT NOT NULL,
  `resolved_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL DEFAULT 'applied',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_stage_transition_run_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_stage_transition_run_input` (`transition_id`, `input_checksum`),
  KEY `idx_jl_stage_transition_run_project` (`project_id`, `created`),
  CONSTRAINT `fk_jl_stage_transition_run_transition` FOREIGN KEY (`transition_id`) REFERENCES `#__joomleague_stage_transition` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_run_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_stage_transition_run_status` CHECK (`status` IN ('applied'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_stage_transition_assignment` (
  `transition_id` BIGINT UNSIGNED NOT NULL,
  `target_stage_id` BIGINT UNSIGNED NOT NULL,
  `project_entry_id` BIGINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `target_seed` INT UNSIGNED NULL DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`transition_id`, `project_entry_id`),
  KEY `idx_jl_stage_transition_assignment_target` (`target_stage_id`, `project_id`, `project_entry_id`),
  KEY `idx_jl_stage_transition_assignment_run` (`run_id`),
  CONSTRAINT `fk_jl_stage_transition_assignment_transition` FOREIGN KEY (`transition_id`) REFERENCES `#__joomleague_stage_transition` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_assignment_stage` FOREIGN KEY (`target_stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_assignment_entry` FOREIGN KEY (`project_entry_id`, `project_id`) REFERENCES `#__joomleague_project_entry` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_stage_transition_assignment_run` FOREIGN KEY (`run_id`) REFERENCES `#__joomleague_stage_transition_run` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_schedule_generation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL, `stage_id` BIGINT UNSIGNED NOT NULL,
  `input_checksum` CHAR(64) NOT NULL, `options_json` LONGTEXT NOT NULL, `round_count` INT UNSIGNED NOT NULL DEFAULT 0, `match_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `conflict_count` INT UNSIGNED NOT NULL DEFAULT 0, `status` VARCHAR(30) NOT NULL DEFAULT 'applied', `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_schedule_generation_uuid` (`uuid`), UNIQUE KEY `uq_jl_schedule_generation_input` (`stage_id`, `input_checksum`), KEY `idx_jl_schedule_generation_project` (`project_id`, `created`),
  CONSTRAINT `fk_jl_schedule_generation_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_schedule_generation_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_schedule_generation_status` CHECK (`status` IN ('applied'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_schedule_generation_match` (
  `generation_id` BIGINT UNSIGNED NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL, `round_sequence` INT UNSIGNED NOT NULL, `match_sequence` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`generation_id`, `match_id`), UNIQUE KEY `uq_jl_schedule_generation_match` (`match_id`),
  CONSTRAINT `fk_jl_schedule_generation_match_generation` FOREIGN KEY (`generation_id`) REFERENCES `#__joomleague_schedule_generation` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_schedule_generation_match_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_migration_batch` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_uuid` CHAR(36) NOT NULL,
  `source_product` VARCHAR(100) NOT NULL,
  `source_version` VARCHAR(100) NOT NULL,
  `source_fingerprint` CHAR(64) NOT NULL,
  `state` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `options_json` LONGTEXT NULL,
  `total_records` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `processed_records` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `imported_records` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `skipped_records` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `failed_records` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `started` DATETIME NULL DEFAULT NULL,
  `finished` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_migration_batch_uuid` (`batch_uuid`),
  UNIQUE KEY `uq_jl_migration_source` (`source_product`, `source_fingerprint`),
  KEY `idx_jl_migration_batch_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_migration_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT UNSIGNED NOT NULL,
  `source_table` VARCHAR(191) NOT NULL,
  `source_identity_json` TEXT NOT NULL,
  `source_identity_hash` CHAR(64) NOT NULL,
  `source_payload_json` LONGTEXT NULL,
  `source_payload_checksum` CHAR(64) NULL,
  `target_entity` VARCHAR(100) NULL,
  `target_identity` VARCHAR(191) NULL,
  `outcome` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `message_code` VARCHAR(191) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_migration_record` (`batch_id`, `source_table`, `source_identity_hash`),
  KEY `idx_jl_migration_record_outcome` (`batch_id`, `outcome`),
  KEY `idx_jl_migration_record_target` (`target_entity`, `target_identity`),
  CONSTRAINT `fk_jl_migration_record_batch`
    FOREIGN KEY (`batch_id`) REFERENCES `#__joomleague_migration_batch` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_migration_issue` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT UNSIGNED NOT NULL,
  `record_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `severity` VARCHAR(20) NOT NULL,
  `issue_code` VARCHAR(191) NOT NULL,
  `message` TEXT NOT NULL,
  `context_json` LONGTEXT NULL,
  `state` VARCHAR(30) NOT NULL DEFAULT 'open',
  `resolution_json` LONGTEXT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved` DATETIME NULL DEFAULT NULL,
  `resolved_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_jl_migration_issue_batch` (`batch_id`, `state`, `severity`),
  KEY `idx_jl_migration_issue_record` (`record_id`),
  CONSTRAINT `fk_jl_migration_issue_batch`
    FOREIGN KEY (`batch_id`) REFERENCES `#__joomleague_migration_batch` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_jl_migration_issue_record`
    FOREIGN KEY (`record_id`) REFERENCES `#__joomleague_migration_record` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
