<?php
declare(strict_types=1);namespace Joomleague\Component\Joomleague\Administrator\Table;\defined('_JEXEC')or die;
use Joomla\CMS\Filter\OutputFilter;use Joomla\CMS\Language\Text;use Joomla\CMS\Table\Asset;use Joomla\CMS\Table\Table;use Joomla\Database\DatabaseInterface;use Joomla\Event\DispatcherInterface;
final class MatchTable extends Table
{
 protected $_supportNullValue=true;public function __construct(DatabaseInterface $d,?DispatcherInterface $x=null){parent::__construct('#__joomleague_match','id',$d,$x);}
 public function check():bool{if(!parent::check())return false;if((int)$this->round_id<1||(int)$this->projectteam1_id<1||(int)$this->projectteam2_id<1){$this->setError(Text::_('COM_JOOMLEAGUE_MATCH_ERROR_REQUIRED'));return false;}if((int)$this->projectteam1_id===(int)$this->projectteam2_id){$this->setError(Text::_('COM_JOOMLEAGUE_MATCH_ERROR_SAME_TEAM'));return false;}if((int)$this->crowd<0){$this->setError(Text::_('COM_JOOMLEAGUE_MATCH_ERROR_CROWD'));return false;}$d=$this->getDatabase();$project=(int)$d->setQuery('SELECT project_id FROM #__joomleague_round WHERE id='.(int)$this->round_id)->loadResult();$valid=(int)$d->setQuery('SELECT COUNT(*) FROM #__joomleague_project_team WHERE project_id='.(int)$project.' AND id IN ('.(int)$this->projectteam1_id.','.(int)$this->projectteam2_id.')')->loadResult();if($valid!==2){$this->setError(Text::_('COM_JOOMLEAGUE_MATCH_ERROR_PROJECT_TEAMS'));return false;}$this->alias=OutputFilter::stringURLSafe(trim((string)$this->alias)?:'match-'.$this->round_id.'-'.$this->projectteam1_id.'-'.$this->projectteam2_id);return true;}
 protected function _getAssetName():string{return 'com_joomleague.match.'.(int)$this->id;}protected function _getAssetTitle():string{return trim((string)$this->match_number)?:'Match '.(int)$this->id;}protected function _getAssetParentId(?Table $table=null,$id=null):int{$asset=new Asset($this->getDatabase(),$this->getDispatcher());return $asset->loadByName('com_joomleague')?(int)$asset->id:parent::_getAssetParentId($table,$id);}
}
