<?php
declare(strict_types=1);namespace Joomleague\Component\Joomleague\Administrator\Model;\defined('_JEXEC')or die;
use Joomla\CMS\Application\AdministratorApplication;use Joomla\Database\QueryInterface;
final class MatchesModel extends EntityListModel
{
 protected array $searchColumns=['a.match_number','th.name','tg.name'];protected string $defaultOrdering='a.match_date';protected string $defaultDirection='ASC';private AdministratorApplication $application;public function setApplication(AdministratorApplication $a):void{$this->application=$a;}
 protected function populateState($o='a.match_date',$d='asc'):void{$input=$this->application->getInput();$id=$input->getInt('round_id');if(!$id){$rid=$input->get('rid',[],'array');$id=(int)($rid[0]??0);}if($id)$this->application->setUserState('com_joomleague.matches.round_id',$id);$this->setState('filter.round_id',$id?:$this->application->getUserState('com_joomleague.matches.round_id'));parent::populateState($o,$d);}
 public function getRoundContext():?object{$rid=(int)$this->getState('filter.round_id');$db=$this->getDatabase();$sql='SELECT r.*,p.name AS project_name,p.timezone,(SELECT id FROM #__joomleague_round x WHERE x.project_id=r.project_id AND x.roundcode<r.roundcode ORDER BY x.roundcode DESC LIMIT 1) AS previous_id,(SELECT id FROM #__joomleague_round x WHERE x.project_id=r.project_id AND x.roundcode>r.roundcode ORDER BY x.roundcode ASC LIMIT 1) AS next_id FROM #__joomleague_round r JOIN #__joomleague_project p ON p.id=r.project_id WHERE r.id='.$rid;return $db->setQuery($sql)->loadObject();}
 protected function buildQuery():QueryInterface{$db=$this->getDatabase();$rid=(int)$this->getState('filter.round_id');return $db->createQuery()->select('a.*,th.name AS home,tg.name AS away,CONCAT(COALESCE(a.team1_result,"-")," : ",COALESCE(a.team2_result,"-")) AS result,u.name AS editor,(SELECT COUNT(*) FROM #__joomleague_match_event e WHERE e.match_id=a.id) AS event_count,(SELECT COUNT(*) FROM #__joomleague_match_player mp WHERE mp.match_id=a.id) AS player_count,(SELECT COUNT(*) FROM #__joomleague_match_statistic s WHERE s.match_id=a.id) AS statistic_count,(SELECT COUNT(*) FROM #__joomleague_match_referee mr WHERE mr.match_id=a.id) AS referee_count,(SELECT COUNT(*) FROM #__content c WHERE c.id=a.article_id AND c.state<>-2) AS has_article')->from('#__joomleague_match a')->join('LEFT','#__joomleague_project_team ph ON ph.id=a.projectteam1_id')->join('LEFT','#__joomleague_team th ON th.id=ph.team_id')->join('LEFT','#__joomleague_project_team pg ON pg.id=a.projectteam2_id')->join('LEFT','#__joomleague_team tg ON tg.id=pg.team_id')->join('LEFT','#__users u ON u.id=a.checked_out')->where('a.round_id='.(int)$rid);}
}
