<?php

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;

HTMLHelper::_('behavior.multiselect'); $user = Factory::getApplication()->getIdentity(); $projectId = (int) $this->project->id; $stageId = (int) $this->state->get('stage_id'); $listOrder = $this->escape($this->state->get('list.ordering')); $listDirn = $this->escape($this->state->get('list.direction'));
?>
<form action="<?php echo Route::_('index.php?option=com_joomleague&view=standingadjustments&project_id=' . $projectId . ($stageId > 0 ? '&stage_id=' . $stageId : '')); ?>" method="post" name="adminForm" id="adminForm">
	<div class="alert alert-info" role="status"><strong><?php echo $this->escape($this->project->name); ?></strong><div><?php echo Text::_('COM_JOOMLEAGUE_STANDING_ADJUSTMENTS_DESC'); ?></div></div><?php echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]); ?>
	<div class="table-responsive"><table class="table table-striped align-middle" id="standingAdjustmentList"><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th class="w-1"><span class="visually-hidden"><?php echo Text::_('JACTION_EDIT'); ?></span></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_ENTRY_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_STANDING_SCOPE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_STANDING_METRIC_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_STANDING_ADJUSTMENT_VALUE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_REASON_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_EFFECTIVE_DATE_LABEL'); ?></th><th class="text-center"><?php echo Text::_('JSTATUS'); ?></th><th class="text-center"><?php echo HTMLHelper::_('searchtools.sort', 'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?></th></tr></thead><tbody>
	<?php foreach ($this->items as $i => $item) : $entryName = $item->team_name ?: (trim((string) $item->first_name . ' ' . (string) $item->last_name) ?: $item->entry_name); $canEdit = $user->authorise('core.edit', 'com_joomleague'); $canChange = $user->authorise('core.edit.state', 'com_joomleague'); ?>
	<tr><td class="text-center"><?php echo HTMLHelper::_('grid.id', $i, (int) $item->id); ?></td><td><?php if ($canEdit) : ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_joomleague&task=standingadjustment.edit&id=' . (int) $item->id . '&project_id=' . $projectId . ($stageId > 0 ? '&stage_id=' . $stageId : '')); ?>" title="<?php echo Text::_('JACTION_EDIT'); ?>"><span class="icon-edit" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('JACTION_EDIT'); ?></span></a><?php endif; ?></td><th scope="row"><?php echo $this->escape($entryName); ?></th><td><?php echo Text::_('COM_JOOMLEAGUE_STANDINGS_SCOPE_' . strtoupper($item->scope_code)); ?></td><td><?php echo Text::_('COM_JOOMLEAGUE_STANDING_METRIC_' . strtoupper($item->metric_code)); ?></td><td><?php echo $this->escape((string) $item->adjustment_value); ?></td><td><?php echo $this->escape($item->reason); ?></td><td><?php echo $item->effective_date ? HTMLHelper::_('date', $item->effective_date, Text::_('DATE_FORMAT_LC4')) : Text::_('JNONE'); ?></td><td class="text-center"><?php echo HTMLHelper::_('jgrid.published', $item->published, $i, 'standingadjustments.', $canChange, 'cb'); ?></td><td class="text-center"><?php echo (int) $item->id; ?></td></tr>
	<?php endforeach; ?><?php if ($this->items === []) : ?><tr><td colspan="10"><div class="alert alert-warning mb-0"><?php echo Text::_('COM_JOOMLEAGUE_STANDING_ADJUSTMENTS_EMPTY'); ?></div></td></tr><?php endif; ?></tbody></table></div><?php echo $this->pagination->getListFooter(); ?>
	<input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="project_id" value="<?php echo $projectId; ?>"><input type="hidden" name="stage_id" value="<?php echo $stageId; ?>"><input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>"><?php echo HTMLHelper::_('form.token'); ?>
</form>
