<?php
declare(strict_types=1);
use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
defined('_JEXEC') or die;$data=$this->overview;$escape=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<div class="com-joomleague-statisticsoverview">
<?php if(isset($data['error'])):?><div class="alert alert-warning"><?php echo Text::_($data['error']);?></div><?php else:?>
<header class="border-bottom pb-3 mb-4"><h1 class="mb-1"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_VIEW_TITLE');?></h1><div class="text-body-secondary"><?php echo$escape($data['project']->name);?></div></header>
<div class="row row-cols-2 row-cols-lg-5 g-3 mb-5"><?php foreach(['entries','programme','completed','event_types','statistic_types']as$metric):?><div class="col"><div class="border rounded p-3 h-100"><div class="fs-3 fw-semibold"><?php echo(int)$data['summary'][$metric];?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_'.strtoupper($metric));?></div></div></div><?php endforeach;?></div>
<?php if((int)$data['attendance']->recorded_count>0):?><section class="mb-5"><h2 class="h4"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_ATTENDANCE');?></h2><div class="row row-cols-1 row-cols-md-3 g-3"><div class="col"><div class="border rounded p-3 h-100"><div class="fs-4 fw-semibold"><?php echo(int)$data['attendance']->recorded_count;?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_ATTENDANCE_RECORDED');?></div></div></div><div class="col"><div class="border rounded p-3 h-100"><div class="fs-4 fw-semibold"><?php echo number_format((float)$data['attendance']->total_value,0,'',' ');?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_ATTENDANCE_TOTAL');?></div></div></div><div class="col"><div class="border rounded p-3 h-100"><div class="fs-4 fw-semibold"><?php echo number_format((float)$data['attendance']->average_value,1,',',' ');?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_ATTENDANCE_AVERAGE');?></div></div></div></div></section><?php endif;?>
<div class="row row-cols-1 row-cols-lg-2 g-4"><section class="col"><h2 class="h4"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_EVENTS');?></h2><?php if($data['event_definitions']===[]):?><div class="alert alert-info"><?php echo Text::_('COM_JOOMLEAGUE_EVENTRANKING_EMPTY');?></div><?php else:?><div class="list-group"><?php foreach($data['event_definitions']as$definition):?><a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="<?php echo Route::_('index.php?option=com_joomleague&view=eventranking&project_id='.(int)$data['project']->id.'&event_code='.rawurlencode((string)$definition->event_code));?>"><span><?php echo$escape(Text::_((string)$definition->name_key));?></span><span class="badge text-bg-secondary"><?php echo(int)$definition->event_count;?></span></a><?php endforeach;?></div><?php endif;?></section><section class="col"><h2 class="h4"><?php echo Text::_('COM_JOOMLEAGUE_STATSOVERVIEW_STATISTICS');?></h2><?php if($data['statistic_definitions']===[]):?><div class="alert alert-info"><?php echo Text::_('COM_JOOMLEAGUE_STATRANKING_EMPTY');?></div><?php else:?><div class="list-group"><?php foreach($data['statistic_definitions']as$definition):?><a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="<?php echo Route::_('index.php?option=com_joomleague&view=statranking&project_id='.(int)$data['project']->id.'&statistic_code='.rawurlencode((string)$definition->statistic_code));?>"><span><?php echo$escape(Text::_((string)$definition->name_key));?></span><span class="badge text-bg-secondary"><?php echo(int)$definition->value_count;?></span></a><?php endforeach;?></div><?php endif;?></section></div>
<?php endif;?>
</div>
