<?php
declare(strict_types=1);
namespace Joomleague\Component\Joomleague\Domain\Service;
defined('_JEXEC') or die;
use Joomla\Database\DatabaseInterface;use Joomla\Database\ParameterType;
/** Read-only sport-neutral event occurrence ranking. */
final class EventRankingReader{public function __construct(private readonly DatabaseInterface $database){}
/** @param list<int> $viewLevels @return array<string,mixed> */
public function forProject(int$projectId,?string$eventCode,int$limit,array$viewLevels):array{if($projectId<1||($eventCode!==null&&preg_match('/^[a-z][a-z0-9_]*$/',$eventCode)!==1))throw new\InvalidArgumentException('Event ranking context is invalid.');$db=$this->database;$levels=array_values(array_unique(array_filter(array_map('intval',$viewLevels),fn(int$id):bool=>$id>0)))?:[1];$access=implode(',',$levels);$project=$db->setQuery($db->getQuery(true)->select(['project.id','project.name'])->from($db->quoteName('#__joomleague_project','project'))->innerJoin($db->quoteName('#__joomleague_competition','competition').' ON competition.id=project.competition_id AND competition.published=1 AND competition.access IN ('.$access.')')->innerJoin($db->quoteName('#__joomleague_season','season').' ON season.id=project.season_id AND season.published=1 AND season.access IN ('.$access.')')->where('project.id=:project')->where('project.published=1')->where('project.access IN ('.$access.')')->bind(':project',$projectId,ParameterType::INTEGER))->loadObject();if(!$project)throw new\RuntimeException('Event ranking project is unavailable.');
$base=$db->getQuery(true)->from($db->quoteName('#__joomleague_match_event','event'))->innerJoin($db->quoteName('#__joomleague_project_match','match').' ON match.id=event.match_id AND match.published=1')->innerJoin($db->quoteName('#__joomleague_match_result','result')." ON result.match_id=match.id AND result.status_code='final'")->where('event.project_id=:project')->where('event.published=1')->where('(event.primary_person_id IS NOT NULL OR event.match_participant_id IS NOT NULL OR event.source_match_actor_role_id IS NOT NULL)')->bind(':project',$projectId,ParameterType::INTEGER);
$definitions=$db->setQuery((clone$base)->select(['event.event_code','MAX(event.event_name_key) AS name_key','COUNT(event.id) AS event_count'])->group('event.event_code')->order('event.event_code ASC'))->loadObjectList();if($definitions===[])return compact('project','definitions')+['selected_code'=>null,'rows'=>[]];$codes=array_map(fn(object$r):string=>(string)$r->event_code,$definitions);if($eventCode===null||!in_array($eventCode,$codes,true))$eventCode=$codes[0];$code=$eventCode;
$kind="CASE WHEN event.primary_person_id IS NOT NULL OR actor.actor_kind = 'person' THEN 'person' WHEN actor.actor_kind = 'team' THEN 'team' ELSE 'participant' END";$id="CASE WHEN event.primary_person_id IS NOT NULL THEN event.primary_person_id WHEN actor.actor_kind = 'person' THEN actor.person_id WHEN actor.actor_kind = 'team' THEN actor.team_id ELSE participant.project_entry_id END";
$query=(clone$base)->select([$kind.' AS target_kind',$id.' AS target_id','MAX(COALESCE(event.primary_name_snapshot,event.actor_name_snapshot,entry.display_name)) AS display_name','COUNT(event.id) AS total_value','COUNT(DISTINCT event.match_id) AS appearances'])->leftJoin($db->quoteName('#__joomleague_match_participant','participant').' ON participant.id=event.match_participant_id AND participant.published=1')->leftJoin($db->quoteName('#__joomleague_project_entry','entry').' ON entry.id=participant.project_entry_id AND entry.published=1')->leftJoin($db->quoteName('#__joomleague_match_actor_role','actor').' ON actor.id=event.source_match_actor_role_id AND actor.published=1')->leftJoin($db->quoteName('#__joomleague_person','primary_person').' ON primary_person.id=event.primary_person_id AND primary_person.published=1 AND primary_person.access IN ('.$access.')')->leftJoin($db->quoteName('#__joomleague_person','actor_person').' ON actor_person.id=actor.person_id AND actor_person.published=1 AND actor_person.access IN ('.$access.')')->leftJoin($db->quoteName('#__joomleague_team','actor_team').' ON actor_team.id=actor.team_id AND actor_team.published=1 AND actor_team.access IN ('.$access.')')->where('event.event_code=:code')->where("((event.primary_person_id IS NOT NULL AND primary_person.id IS NOT NULL) OR (event.primary_person_id IS NULL AND actor.actor_kind='person' AND actor_person.id IS NOT NULL) OR (event.primary_person_id IS NULL AND actor.actor_kind='team' AND actor_team.id IS NOT NULL) OR (event.primary_person_id IS NULL AND actor.id IS NULL AND participant.id IS NOT NULL))")->group([$kind,$id])->order(['total_value DESC','display_name ASC'])->bind(':code',$code);$rows=$db->setQuery($query,0,min(500,max(1,$limit)))->loadObjectList();foreach($rows as$i=>$row)$row->rank=$i+1;return compact('project','definitions','rows')+['selected_code'=>$eventCode];}}
