<?php
declare(strict_types=1);namespace Joomleague\Component\Joomleague\Domain\Service;defined('_JEXEC')or die;
use Joomla\Database\DatabaseInterface;use Joomla\Database\ParameterType;
final class PersonnelReader
{
	public function __construct(private readonly DatabaseInterface$db){}
	/** @param list<int>$viewLevels @return array<string,mixed> */
	public function forProject(int$projectId,array$viewLevels):array
	{
		if($projectId<1)return['error'=>'project_required'];$levels=array_values(array_unique(array_filter(array_map('intval',$viewLevels),static fn(int$id):bool=>$id>0)));$access=implode(',',$levels?:[1]);$db=$this->db;
		$project=$db->setQuery($db->getQuery(true)->select(['project.id','project.name','sport_type.name AS sport_type_name','version.payload_json AS profile_json'])->from($db->quoteName('#__joomleague_project','project'))->innerJoin($db->quoteName('#__joomleague_competition','competition').' ON competition.id=project.competition_id AND competition.published=1')->innerJoin($db->quoteName('#__joomleague_season','season').' ON season.id=project.season_id AND season.published=1')->innerJoin($db->quoteName('#__joomleague_sport_type','sport_type').' ON sport_type.id=project.sport_type_id AND sport_type.published=1')->innerJoin($db->quoteName('#__joomleague_sport_profile_version','version').' ON version.id=project.profile_version_id')->where('project.id=:projectId')->where('project.published=1')->where('project.access IN ('.$access.')')->where('competition.access IN ('.$access.')')->where('season.access IN ('.$access.')')->bind(':projectId',$projectId,ParameterType::INTEGER))->loadObject();if(!$project)return['error'=>'project_unavailable'];
		$labels=[];$profile=json_decode((string)$project->profile_json,true);foreach(is_array($profile)?($profile['positions']??[]):[]as$position)if(is_array($position)&&is_string($position['code']??null)&&is_string($position['name_key']??null))$labels[$position['code']]=$position['name_key'];unset($project->profile_json);$groups=['staff'=>[],'official'=>[]];
		$type='staff';$staff=$db->setQuery($db->getQuery(true)->select(['member.person_id','member.role_code','person.first_name','person.last_name','person.nickname','person.picture','entry.id AS entry_id'])->from($db->quoteName('#__joomleague_project_entry_member','member'))->innerJoin($db->quoteName('#__joomleague_project_entry','entry').' ON entry.id=member.entry_id AND entry.published=1')->innerJoin($db->quoteName('#__joomleague_person','person').' ON person.id=member.person_id AND person.published=1 AND person.access IN ('.$access.')')->where('entry.project_id=:projectId')->where('member.published=1')->where('member.member_person_type=:personType')->bind(':projectId',$projectId,ParameterType::INTEGER)->bind(':personType',$type)->order('member.ordering ASC,person.last_name ASC,person.first_name ASC,member.id ASC'))->loadObjectList();foreach($staff as$row)$this->append($groups['staff'],$row,$labels,'staff');
		$kind='person';$count=$db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__joomleague_match_actor_role','match_role'))->innerJoin($db->quoteName('#__joomleague_project_match','item').' ON item.id=match_role.match_id AND item.published=1')->where('match_role.project_id=role.project_id')->where('match_role.person_id=role.person_id')->where('match_role.role_code=role.role_code')->where('match_role.published=1');$officials=$db->setQuery($db->getQuery(true)->select(['role.person_id','role.role_code','person.first_name','person.last_name','person.nickname','person.picture','('.$count.') AS assignment_count'])->from($db->quoteName('#__joomleague_project_actor_role','role'))->innerJoin($db->quoteName('#__joomleague_person','person').' ON person.id=role.person_id AND person.published=1 AND person.access IN ('.$access.')')->where('role.project_id=:projectId')->where('role.actor_kind=:actorKind')->where('role.published=1')->bind(':projectId',$projectId,ParameterType::INTEGER)->bind(':actorKind',$kind)->order('role.ordering ASC,person.last_name ASC,person.first_name ASC,role.id ASC'))->loadObjectList();foreach($officials as$row)$this->append($groups['official'],$row,$labels,'official');return['project'=>$project,'groups'=>$groups];
	}
	/** @param array<string,object>$target @param array<string,string>$labels */
	private function append(array&$target,object$row,array$labels,string$type):void{$key=(int)$row->person_id.':'.(string)$row->role_code;if(!isset($target[$key]))$target[$key]=(object)['person_id'=>(int)$row->person_id,'name'=>trim((string)$row->first_name.' '.(string)$row->last_name),'nickname'=>(string)$row->nickname,'picture'=>(string)$row->picture,'role_code'=>(string)$row->role_code,'role_label'=>$labels[(string)$row->role_code]??'','person_type'=>$type,'entry_count'=>0,'assignment_count'=>(int)($row->assignment_count??0)];if(isset($row->entry_id))$target[$key]->entry_count++;}
}
