<?php
declare(strict_types=1);namespace Joomleague\Component\Joomleague\Domain\Service;defined('_JEXEC')or die;use Joomla\Database\DatabaseInterface;use Joomla\Database\ParameterType;
final class ProjectCatalogueReader
{
	public function __construct(private readonly DatabaseInterface$db){}
	/** @param list<int>$viewLevels @return list<object> */
	public function read(array$viewLevels,int$sportTypeId=0,int$seasonId=0,string$organisation='',int$limit=0):array
	{
		$levels=array_values(array_unique(array_filter(array_map('intval',$viewLevels),static fn(int$id):bool=>$id>0)));$access=implode(',',$levels?:[1]);$db=$this->db;$entryCount=$db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__joomleague_project_entry','entry'))->leftJoin($db->quoteName('#__joomleague_team','entry_team').' ON entry_team.id=entry.team_id AND entry_team.published=1 AND entry_team.access IN ('.$access.')')->leftJoin($db->quoteName('#__joomleague_person','entry_person').' ON entry_person.id=entry.person_id AND entry_person.published=1 AND entry_person.access IN ('.$access.')')->where('entry.project_id=project.id')->where('entry.published=1')->where("(entry.entry_kind='group' OR (entry.entry_kind='team' AND entry_team.id IS NOT NULL) OR (entry.entry_kind='person' AND entry_person.id IS NOT NULL))");$matchCount=$db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__joomleague_project_match','match_item'))->where('match_item.project_id=project.id')->where('match_item.published=1');
		$q=$db->getQuery(true)->select(['project.id','project.name','project.alias','project.description','project.picture','project.start_date','project.end_date','project.project_type','competition.name AS competition_name','competition.organisation','season.name AS season_name','sport_type.name AS sport_type_name','('.$entryCount.') AS entry_count','('.$matchCount.') AS match_count'])->from($db->quoteName('#__joomleague_project','project'))->innerJoin($db->quoteName('#__joomleague_competition','competition').' ON competition.id=project.competition_id AND competition.published=1')->innerJoin($db->quoteName('#__joomleague_season','season').' ON season.id=project.season_id AND season.published=1')->innerJoin($db->quoteName('#__joomleague_sport_type','sport_type').' ON sport_type.id=project.sport_type_id AND sport_type.published=1')->where('project.published=1')->where('project.access IN ('.$access.')')->where('competition.access IN ('.$access.')')->where('season.access IN ('.$access.')')->order('project.ordering ASC,project.id DESC');
		if($sportTypeId>0)$q->where('project.sport_type_id=:sport')->bind(':sport',$sportTypeId,ParameterType::INTEGER);if($seasonId>0)$q->where('project.season_id=:season')->bind(':season',$seasonId,ParameterType::INTEGER);$organisation=trim($organisation);if($organisation!=='')$q->where('competition.organisation=:organisation')->bind(':organisation',$organisation);return$db->setQuery($q,0,$limit>0?min(100,$limit):0)->loadObjectList();
	}
}
