<?php
declare(strict_types=1);
use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
defined('_JEXEC') or die;$data=$this->progression;$escape=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<div class="com-joomleague-standingprogression">
<?php if(isset($data['error'])):?><div class="alert alert-warning"><?php echo Text::_($data['error']);?></div><?php else:?>
<header class="border-bottom pb-3 mb-4"><h1 class="mb-1"><?php echo Text::_('COM_JOOMLEAGUE_PROGRESSION_VIEW_TITLE');?></h1><div class="text-body-secondary"><?php echo$escape($data['project']->name);?><?php if($data['stage']):?> <span aria-hidden="true">&middot;</span> <?php echo$escape($data['stage']->name);?><?php endif;?></div></header>
<?php if(count($data['available_scopes'])>1):?><nav class="nav nav-pills gap-2 mb-4" aria-label="<?php echo Text::_('COM_JOOMLEAGUE_PROGRESSION_SCOPE');?>"><?php foreach($data['available_scopes']as$scope):?><a class="nav-link<?php echo$scope===$data['scope']?' active':'';?>" href="<?php echo Route::_('index.php?option=com_joomleague&view=standingprogression&project_id='.(int)$data['project']->id.($data['stage']?'&stage_id='.(int)$data['stage']->id:'').'&scope='.rawurlencode($scope));?>"><?php echo$escape($scope);?></a><?php endforeach;?></nav><?php endif;?>
<?php if($data['points']===[]):?><div class="alert alert-info"><?php echo Text::_('COM_JOOMLEAGUE_PROGRESSION_EMPTY');?></div><?php else:?><div class="table-responsive w-100"><table class="table table-striped table-hover align-middle text-center"><thead><tr><th scope="col" class="text-start"><?php echo Text::_('COM_JOOMLEAGUE_PROGRESSION_PARTICIPANT');?></th><?php foreach($data['points']as$point):?><th scope="col"><?php echo$escape($point['round_name']);?></th><?php endforeach;?></tr></thead><tbody><?php foreach($data['entries']as$entry):?><tr><th scope="row" class="text-start"><a href="<?php echo Route::_('index.php?option=com_joomleague&view=participant&project_id='.(int)$data['project']->id.'&entry_id='.(int)$entry['id']);?>"><?php echo$escape($entry['name']);?></a></th><?php foreach($data['points']as$point):$rank=$point['ranks'][(int)$entry['id']]??null;$change=$point['changes'][(int)$entry['id']]??0;?><td><?php if($rank===null):?><span class="text-body-secondary">&mdash;</span><?php else:?><span class="badge text-bg-secondary"><?php echo(int)$rank;?></span><?php if($change!==0):$changeLabel=Text::sprintf('COM_JOOMLEAGUE_PROGRESSION_CHANGE',$change);?><span class="ms-1 <?php echo$change>0?'text-success':'text-danger';?>" title="<?php echo$escape($changeLabel);?>" aria-label="<?php echo$escape($changeLabel);?>"><span aria-hidden="true"><span class="icon-arrow-<?php echo$change>0?'up':'down';?>"></span><?php echo abs((int)$change);?></span></span><?php endif;?><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?>
</div>
