<?php

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;

HTMLHelper::_('behavior.multiselect'); $user = Factory::getApplication()->getIdentity(); $stageId = (int) $this->stage->id; $listOrder = $this->escape($this->state->get('list.ordering')); $listDirn = $this->escape($this->state->get('list.direction'));
?>
<form action="<?php echo Route::_('index.php?option=com_joomleague&view=rounds&stage_id=' . $stageId); ?>" method="post" name="adminForm" id="adminForm">
	<div class="alert alert-info" role="status"><strong><?php echo $this->escape($this->stage->project_name); ?></strong><span class="mx-2">/</span><?php echo $this->escape($this->stage->name); ?></div><?php echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]); ?>
	<div class="table-responsive"><table class="table table-striped" id="roundList"><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th class="w-1"><span class="visually-hidden"><?php echo Text::_('JACTION_EDIT'); ?></span></th><th class="text-center"><?php echo HTMLHelper::_('searchtools.sort', 'COM_JOOMLEAGUE_FIELD_ROUND_NUMBER_LABEL', 'a.sequence_number', $listDirn, $listOrder); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_NAME_LABEL'); ?></th><th class="w-1"><span class="visually-hidden"><?php echo Text::_('COM_JOOMLEAGUE_ROUND_MATCHES_MANAGE'); ?></span></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_ROUND_TYPE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_DATE_RANGE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_LIFECYCLE_STATE_LABEL'); ?></th><th class="text-center"><?php echo Text::_('JSTATUS'); ?></th><th class="text-center"><?php echo HTMLHelper::_('searchtools.sort', 'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?></th></tr></thead><tbody>
	<?php foreach ($this->items as $i => $item) : $canEdit = $user->authorise('core.edit', 'com_joomleague'); $canChange = $user->authorise('core.edit.state', 'com_joomleague'); $checkedOut = (int) $item->checked_out !== 0 && (int) $item->checked_out !== (int) $user->id; ?>
	<tr><td class="text-center"><?php echo HTMLHelper::_('grid.id', $i, (int) $item->id); ?></td><td><?php if ($canEdit && !$checkedOut) : ?><a class="btn btn-sm btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_joomleague&task=round.edit&id=' . (int) $item->id . '&stage_id=' . $stageId); ?>" title="<?php echo Text::_('JACTION_EDIT'); ?>"><span class="icon-edit" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('JACTION_EDIT'); ?></span></a><?php endif; ?></td><td class="text-center"><?php echo (int) $item->sequence_number; ?></td><th scope="row"><a href="<?php echo Route::_('index.php?option=com_joomleague&task=round.edit&id=' . (int) $item->id . '&stage_id=' . $stageId); ?>"><?php echo $this->escape($item->name); ?></a><div class="small text-body-secondary"><?php echo $this->escape($item->code); ?></div></th><td><a class="btn btn-sm btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_joomleague&view=matches&round_id=' . (int) $item->id); ?>" title="<?php echo Text::_('COM_JOOMLEAGUE_ROUND_MATCHES_MANAGE'); ?>"><span class="icon-play" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('COM_JOOMLEAGUE_ROUND_MATCHES_MANAGE'); ?></span></a></td><td><?php echo $this->escape($item->round_type); ?></td><td><?php echo Text::sprintf('COM_JOOMLEAGUE_STAGE_DATE_RANGE_VALUE', $item->start_date ?: Text::_('JNONE'), $item->end_date ?: Text::_('JNONE')); ?></td><td><?php echo Text::_('COM_JOOMLEAGUE_LIFECYCLE_' . strtoupper($item->lifecycle_state)); ?></td><td class="text-center"><?php echo HTMLHelper::_('jgrid.published', $item->published, $i, 'rounds.', $canChange, 'cb'); ?></td><td class="text-center"><?php echo (int) $item->id; ?></td></tr>
	<?php endforeach; ?><?php if ($this->items === []) : ?><tr><td colspan="10"><div class="alert alert-warning mb-0"><?php echo Text::_('COM_JOOMLEAGUE_ROUNDS_EMPTY'); ?></div></td></tr><?php endif; ?></tbody></table></div><?php echo $this->pagination->getListFooter(); ?>
	<input type="hidden" name="task" value=""><input type="hidden" name="boxchecked" value="0"><input type="hidden" name="stage_id" value="<?php echo $stageId; ?>"><input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>"><input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>"><?php echo HTMLHelper::_('form.token'); ?>
</form>
