<?php

declare(strict_types=1);

define('_JEXEC', 1);define('JPATH_BASE','/var/www/html');require_once JPATH_BASE.'/includes/defines.php';require_once JPATH_BASE.'/includes/framework.php';
foreach(['UuidFactory.php','CanonicalJson.php','StandingsContractValidator.php','SportProfileSchemaValidator.php','EntryModelValidator.php','MatchResultValidationException.php','MatchResultDecimal.php','MatchResultAggregationValidator.php','MatchResultPayloadValidator.php','MatchResultRepository.php','ScheduleTemplateService.php','SchedulePlannerService.php','ProjectPreflightService.php']as$service)require_once JPATH_ADMINISTRATOR.'/components/com_joomleague/src/Service/'.$service;
use Joomla\CMS\Factory;use Joomla\Database\DatabaseInterface;use Joomleague\Component\Joomleague\Administrator\Service\ProjectPreflightService;use Joomleague\Component\Joomleague\Administrator\Service\SchedulePlannerService;use Joomleague\Component\Joomleague\Domain\Service\UuidFactory;
$container=Factory::getContainer();$container->alias('session','session.cli')->alias('JSession','session.cli')->alias(Joomla\CMS\Session\Session::class,'session.cli')->alias(Joomla\Session\Session::class,'session.cli')->alias(Joomla\Session\SessionInterface::class,'session.cli');Factory::$application=$container->get(Joomla\Console\Application::class);$db=$container->get(DatabaseInterface::class);$suffix=bin2hex(random_bytes(5));$name='Preflight fixture '.$suffix;
$insert=static function(string$table,array$values)use($db):int{$query=$db->getQuery(true)->insert($db->quoteName($table))->columns($db->quoteName(array_keys($values)));$holders=[];foreach($values as$key=>&$value){$holders[]=':'.$key;$query->bind(':'.$key,$value);}$query->values(implode(',',$holders));$db->setQuery($query)->execute();return(int)$db->insertid();};$delete=static function(string$table,string$column,mixed$value)use($db):void{$query=$db->getQuery(true)->delete($db->quoteName($table))->where($db->quoteName($column).'=:value')->bind(':value',$value);$db->setQuery($query)->execute();};
$query=$db->getQuery(true)->select('version.id')->from($db->quoteName('#__joomleague_sport_profile_version','version'))->innerJoin($db->quoteName('#__joomleague_sport_profile','profile').' ON profile.id=version.profile_id')->where('profile.code='.$db->quote('football'))->where('version.state='.$db->quote('active'))->order('version.id DESC');$versionId=(int)$db->setQuery($query,0,1)->loadResult();$competitionId=$insert('#__joomleague_competition',['uuid'=>UuidFactory::v4(),'name'=>$name]);$seasonId=$insert('#__joomleague_season',['uuid'=>UuidFactory::v4(),'name'=>$name]);$sportTypeId=$insert('#__joomleague_sport_type',['profile_version_id'=>$versionId,'code'=>'preflight-'.$suffix,'name'=>$name]);$projectId=$insert('#__joomleague_project',['uuid'=>UuidFactory::v4(),'competition_id'=>$competitionId,'season_id'=>$seasonId,'sport_type_id'=>$sportTypeId,'profile_version_id'=>$versionId,'name'=>$name,'project_type'=>'league','timezone'=>'Europe/Prague']);
try{$service=new ProjectPreflightService($db);$empty=$service->inspect($projectId);if($empty['ready']||$empty['summary']['error']<3)throw new RuntimeException('Empty project was considered ready.');$teamIds=[];for($seed=1;$seed<=4;$seed++){$teamIds[]=$teamId=$insert('#__joomleague_team',['uuid'=>UuidFactory::v4(),'name'=>$name.' '.$seed]);$insert('#__joomleague_project_entry',['uuid'=>UuidFactory::v4(),'project_id'=>$projectId,'entry_kind'=>'team','team_id'=>$teamId,'seed_number'=>$seed]);}$stageId=$insert('#__joomleague_project_stage',['uuid'=>UuidFactory::v4(),'project_id'=>$projectId,'name'=>'League','code'=>'league','stage_type'=>'league']);$planner=new SchedulePlannerService($db);$options=$planner->defaults($stageId);$options['template_id']='round-robin-first-half-v1';$options['start_date']='2026-09-01';$options['start_time']='17:00';$planner->apply($stageId,$options,0);$ready=$service->inspect($projectId);if(!$ready['ready']||$ready['summary']['error']!==0)throw new RuntimeException('Complete project did not pass preflight: '.json_encode($ready['sections'],JSON_THROW_ON_ERROR));$query=$db->getQuery(true)->select('MIN(id)')->from($db->quoteName('#__joomleague_match_participant'))->where('project_id='.(int)$projectId);$participantId=(int)$db->setQuery($query)->loadResult();$delete('#__joomleague_match_participant','id',$participantId);$broken=$service->inspect($projectId);$codes=[];foreach($broken['sections']as$section)foreach($section['checks']as$check)$codes[]=$check['code'];if($broken['ready']||!in_array('match_participants',$codes,true))throw new RuntimeException('Invalid match participant count was not detected.');echo "Project preflight integration passed.\n";}finally{$delete('#__joomleague_project','id',$projectId);foreach($teamIds??[]as$teamId)$delete('#__joomleague_team','id',$teamId);$delete('#__joomleague_sport_type','id',$sportTypeId);$delete('#__joomleague_season','id',$seasonId);$delete('#__joomleague_competition','id',$competitionId);}
