CREATE TABLE IF NOT EXISTS `#__joomleague_organization_name_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_to` DATE NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_org_name_history_uuid` (`uuid`),
  KEY `idx_jl_org_name_history_club` (`club_id`, `valid_from`, `ordering`),
  KEY `idx_jl_org_name_history_team` (`team_id`, `valid_from`, `ordering`),
  CONSTRAINT `fk_jl_org_name_history_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_org_name_history_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_org_name_history_owner` CHECK ((`club_id` IS NOT NULL AND `team_id` IS NULL) OR (`club_id` IS NULL AND `team_id` IS NOT NULL)),
  CONSTRAINT `chk_jl_org_name_history_dates` CHECK (`valid_to` IS NULL OR `valid_from` IS NULL OR `valid_to` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_organization_media_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `media_type` VARCHAR(100) NOT NULL DEFAULT 'logo',
  `media_path` VARCHAR(255) NOT NULL,
  `alt_text` VARCHAR(255) NOT NULL DEFAULT '',
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_to` DATE NULL DEFAULT NULL,
  `notes` TEXT NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_org_media_history_uuid` (`uuid`),
  KEY `idx_jl_org_media_history_club` (`club_id`, `media_type`, `valid_from`, `ordering`),
  KEY `idx_jl_org_media_history_team` (`team_id`, `media_type`, `valid_from`, `ordering`),
  CONSTRAINT `fk_jl_org_media_history_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_org_media_history_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_jl_org_media_history_owner` CHECK ((`club_id` IS NOT NULL AND `team_id` IS NULL) OR (`club_id` IS NULL AND `team_id` IS NOT NULL)),
  CONSTRAINT `chk_jl_org_media_history_dates` CHECK (`valid_to` IS NULL OR `valid_from` IS NULL OR `valid_to` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
