CREATE TABLE IF NOT EXISTS `#__joomleague_club` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `founded_date` DATE NULL DEFAULT NULL,
  `dissolved_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_club_uuid` (`uuid`),
  KEY `idx_jl_club_state` (`published`, `ordering`),
  CONSTRAINT `chk_jl_club_dates` CHECK (`dissolved_date` IS NULL OR `founded_date` IS NULL OR `dissolved_date` >= `founded_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_team` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(100) NOT NULL DEFAULT '',
  `short_name` VARCHAR(50) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_team_uuid` (`uuid`),
  KEY `idx_jl_team_club` (`club_id`),
  KEY `idx_jl_team_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_team_club` FOREIGN KEY (`club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_person` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `contact_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NOT NULL DEFAULT '',
  `last_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nickname` VARCHAR(100) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `death_date` DATE NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_person_uuid` (`uuid`),
  KEY `idx_jl_person_name` (`last_name`, `first_name`),
  KEY `idx_jl_person_state` (`published`, `ordering`),
  CONSTRAINT `chk_jl_person_dates` CHECK (`death_date` IS NULL OR `birth_date` IS NULL OR `death_date` >= `birth_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_entry` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `entry_kind` VARCHAR(20) NOT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `display_name` VARCHAR(255) NOT NULL DEFAULT '',
  `entry_code` VARCHAR(100) NULL DEFAULT NULL,
  `seed_number` INT UNSIGNED NULL DEFAULT NULL,
  `bib_number` VARCHAR(50) NULL DEFAULT NULL,
  `included_in_standings` TINYINT NOT NULL DEFAULT 1,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_entry_uuid` (`uuid`),
  UNIQUE KEY `uq_jl_project_entry_team` (`project_id`, `team_id`),
  UNIQUE KEY `uq_jl_project_entry_person` (`project_id`, `person_id`),
  KEY `idx_jl_project_entry_state` (`project_id`, `published`, `ordering`),
  CONSTRAINT `fk_jl_project_entry_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_project_entry_team` FOREIGN KEY (`team_id`) REFERENCES `#__joomleague_team` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_entry_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_project_entry_kind` CHECK (`entry_kind` IN ('team', 'person', 'group')),
  CONSTRAINT `chk_jl_project_entry_target` CHECK ((`entry_kind` = 'team' AND `team_id` IS NOT NULL AND `person_id` IS NULL) OR (`entry_kind` = 'person' AND `person_id` IS NOT NULL AND `team_id` IS NULL) OR (`entry_kind` = 'group' AND `team_id` IS NULL AND `person_id` IS NULL AND `display_name` <> ''))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_entry_member` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `entry_id` BIGINT UNSIGNED NOT NULL,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `member_person_type` VARCHAR(50) NOT NULL,
  `role_code` VARCHAR(100) NULL DEFAULT NULL,
  `shirt_number` VARCHAR(20) NULL DEFAULT NULL,
  `is_captain` TINYINT NOT NULL DEFAULT 0,
  `valid_from` DATE NULL DEFAULT NULL,
  `valid_until` DATE NULL DEFAULT NULL,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_entry_member_uuid` (`uuid`),
  KEY `idx_jl_entry_member_entry` (`entry_id`, `published`, `ordering`),
  KEY `idx_jl_entry_member_person` (`person_id`, `valid_from`, `valid_until`),
  CONSTRAINT `fk_jl_entry_member_entry` FOREIGN KEY (`entry_id`) REFERENCES `#__joomleague_project_entry` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_entry_member_person` FOREIGN KEY (`person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_entry_member_dates` CHECK (`valid_until` IS NULL OR `valid_from` IS NULL OR `valid_until` >= `valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
