CREATE TABLE IF NOT EXISTS `#__joomleague_venue` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `owner_club_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `short_name` VARCHAR(100) NOT NULL DEFAULT '',
  `nickname` VARCHAR(100) NOT NULL DEFAULT '',
  `address` VARCHAR(255) NOT NULL DEFAULT '',
  `postal_code` VARCHAR(20) NOT NULL DEFAULT '',
  `city` VARCHAR(100) NOT NULL DEFAULT '',
  `region` VARCHAR(100) NOT NULL DEFAULT '',
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `timezone` VARCHAR(64) NULL DEFAULT NULL,
  `capacity` BIGINT UNSIGNED NULL DEFAULT NULL,
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_venue_uuid` (`uuid`),
  KEY `idx_jl_venue_owner_club` (`owner_club_id`),
  KEY `idx_jl_venue_state` (`published`, `ordering`),
  CONSTRAINT `fk_jl_venue_owner_club` FOREIGN KEY (`owner_club_id`) REFERENCES `#__joomleague_club` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_venue_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
  CONSTRAINT `chk_jl_venue_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
