CREATE TABLE IF NOT EXISTS `#__joomleague_standing_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL, `stage_id` BIGINT UNSIGNED NULL DEFAULT NULL, `stage_key` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `scope_code` VARCHAR(100) NOT NULL, `standings_type` VARCHAR(100) NOT NULL, `profile_version_id` BIGINT UNSIGNED NOT NULL, `profile_checksum` CHAR(64) NOT NULL, `input_checksum` CHAR(64) NOT NULL, `contract_json` LONGTEXT NOT NULL,
  `row_count` INT UNSIGNED NOT NULL DEFAULT 0, `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `generated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_standing_snapshot_uuid` (`uuid`), UNIQUE KEY `uq_jl_standing_snapshot_input` (`project_id`, `stage_key`, `scope_code`, `input_checksum`), UNIQUE KEY `uq_jl_standing_snapshot_owner` (`id`, `project_id`), KEY `idx_jl_standing_snapshot_stage` (`stage_id`, `generated_at`),
  CONSTRAINT `fk_jl_standing_snapshot_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_jl_standing_snapshot_stage` FOREIGN KEY (`stage_id`, `project_id`) REFERENCES `#__joomleague_project_stage` (`id`, `project_id`) ON DELETE CASCADE, CONSTRAINT `fk_jl_standing_snapshot_profile` FOREIGN KEY (`profile_version_id`) REFERENCES `#__joomleague_sport_profile_version` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_standing_snapshot_stage` CHECK ((`stage_id` IS NULL AND `stage_key` = 0) OR (`stage_id` IS NOT NULL AND `stage_key` = `stage_id`)), CONSTRAINT `chk_jl_standing_snapshot_rows` CHECK (`row_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `#__joomleague_standing_snapshot_row` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `snapshot_id` BIGINT UNSIGNED NOT NULL, `project_entry_id` BIGINT UNSIGNED NULL DEFAULT NULL, `entry_id_snapshot` BIGINT UNSIGNED NOT NULL, `entry_name_snapshot` VARCHAR(255) NOT NULL, `rank_number` INT UNSIGNED NOT NULL, `sequence_number` INT UNSIGNED NOT NULL, `metrics_json` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_standing_row_entry` (`snapshot_id`, `entry_id_snapshot`), KEY `idx_jl_standing_row_order` (`snapshot_id`, `sequence_number`), KEY `idx_jl_standing_row_entry` (`project_entry_id`), CONSTRAINT `fk_jl_standing_row_snapshot` FOREIGN KEY (`snapshot_id`) REFERENCES `#__joomleague_standing_snapshot` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_jl_standing_row_entry` FOREIGN KEY (`project_entry_id`) REFERENCES `#__joomleague_project_entry` (`id`) ON DELETE SET NULL, CONSTRAINT `chk_jl_standing_row_rank` CHECK (`rank_number` > 0 AND `sequence_number` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `#__joomleague_standing_current` (
  `project_id` BIGINT UNSIGNED NOT NULL, `stage_key` BIGINT UNSIGNED NOT NULL DEFAULT 0, `scope_code` VARCHAR(100) NOT NULL, `snapshot_id` BIGINT UNSIGNED NOT NULL, `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`project_id`, `stage_key`, `scope_code`), UNIQUE KEY `uq_jl_standing_current_snapshot` (`snapshot_id`), CONSTRAINT `fk_jl_standing_current_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE, CONSTRAINT `fk_jl_standing_current_snapshot` FOREIGN KEY (`snapshot_id`, `project_id`) REFERENCES `#__joomleague_standing_snapshot` (`id`, `project_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
