CREATE TABLE IF NOT EXISTS `#__joomleague_match_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `match_id` BIGINT UNSIGNED NOT NULL, `project_id` BIGINT UNSIGNED NOT NULL,
  `match_participant_id` BIGINT UNSIGNED NULL DEFAULT NULL, `source_event_type_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `event_code` VARCHAR(100) NOT NULL, `event_name_key` VARCHAR(255) NOT NULL, `event_person_type` VARCHAR(100) NULL DEFAULT NULL, `sequence_number` INT UNSIGNED NOT NULL,
  `primary_lineup_member_id` BIGINT UNSIGNED NULL DEFAULT NULL, `primary_person_id` BIGINT UNSIGNED NULL DEFAULT NULL, `primary_name_snapshot` VARCHAR(255) NULL DEFAULT NULL,
  `secondary_lineup_member_id` BIGINT UNSIGNED NULL DEFAULT NULL, `secondary_person_id` BIGINT UNSIGNED NULL DEFAULT NULL, `secondary_name_snapshot` VARCHAR(255) NULL DEFAULT NULL,
  `source_match_actor_role_id` BIGINT UNSIGNED NULL DEFAULT NULL, `actor_name_snapshot` VARCHAR(255) NULL DEFAULT NULL, `score_segment_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `phase_code` VARCHAR(100) NULL DEFAULT NULL, `phase_sequence` INT UNSIGNED NULL DEFAULT NULL, `clock_value` DECIMAL(30,9) NULL DEFAULT NULL, `clock_unit` VARCHAR(50) NULL DEFAULT NULL,
  `occurred_at` DATETIME NULL DEFAULT NULL, `numeric_value` DECIMAL(30,9) NULL DEFAULT NULL, `text_value` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL, `profile_metadata_json` LONGTEXT NOT NULL, `metadata_json` LONGTEXT NULL, `published` TINYINT NOT NULL DEFAULT 1, `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0, `modified` DATETIME NULL DEFAULT NULL, `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_jl_match_event_uuid` (`uuid`), UNIQUE KEY `uq_jl_match_event_sequence` (`match_id`, `sequence_number`),
  KEY `idx_jl_match_event_timeline` (`match_id`, `phase_code`, `phase_sequence`, `clock_value`, `sequence_number`), KEY `idx_jl_match_event_participant` (`match_participant_id`, `event_code`),
  KEY `idx_jl_match_event_primary_person` (`primary_person_id`), KEY `idx_jl_match_event_secondary_person` (`secondary_person_id`), KEY `idx_jl_match_event_actor` (`source_match_actor_role_id`),
  CONSTRAINT `fk_jl_match_event_match` FOREIGN KEY (`match_id`, `project_id`) REFERENCES `#__joomleague_project_match` (`id`, `project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_event_participant` FOREIGN KEY (`match_participant_id`, `match_id`) REFERENCES `#__joomleague_match_participant` (`id`, `match_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_jl_match_event_catalog` FOREIGN KEY (`source_event_type_id`) REFERENCES `#__joomleague_event_type` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_primary_lineup` FOREIGN KEY (`primary_lineup_member_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_primary_person` FOREIGN KEY (`primary_person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_event_secondary_lineup` FOREIGN KEY (`secondary_lineup_member_id`) REFERENCES `#__joomleague_match_lineup_member` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_secondary_person` FOREIGN KEY (`secondary_person_id`) REFERENCES `#__joomleague_person` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_match_event_actor` FOREIGN KEY (`source_match_actor_role_id`) REFERENCES `#__joomleague_match_actor_role` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_jl_match_event_segment` FOREIGN KEY (`score_segment_id`) REFERENCES `#__joomleague_match_score_segment` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_jl_match_event_sequence` CHECK (`sequence_number` > 0), CONSTRAINT `chk_jl_match_event_phase` CHECK (`phase_sequence` IS NULL OR `phase_sequence` > 0),
  CONSTRAINT `chk_jl_match_event_clock` CHECK (`clock_value` IS NULL OR `clock_value` >= 0),
  CONSTRAINT `chk_jl_match_event_primary_snapshot` CHECK ((`primary_person_id` IS NULL AND `primary_name_snapshot` IS NULL) OR (`primary_person_id` IS NOT NULL AND `primary_name_snapshot` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_event_secondary_snapshot` CHECK ((`secondary_person_id` IS NULL AND `secondary_name_snapshot` IS NULL) OR (`secondary_person_id` IS NOT NULL AND `secondary_name_snapshot` IS NOT NULL)),
  CONSTRAINT `chk_jl_match_event_people` CHECK (`secondary_person_id` IS NULL OR (`primary_person_id` IS NOT NULL AND `secondary_person_id` <> `primary_person_id`)),
  CONSTRAINT `chk_jl_match_event_clock_unit` CHECK ((`clock_value` IS NULL AND `clock_unit` IS NULL) OR (`clock_value` IS NOT NULL AND `clock_unit` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
