-- uq_jl_sport_type_profile_binding is ensured idempotently by installer preflight.
CREATE TABLE IF NOT EXISTS `#__joomleague_competition` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(100) NOT NULL DEFAULT '',
  `short_name` VARCHAR(50) NOT NULL DEFAULT '',
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `organisation` VARCHAR(255) NULL DEFAULT NULL,
  `country_code` VARCHAR(8) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_competition_uuid` (`uuid`),
  KEY `idx_jl_competition_code` (`code`),
  KEY `idx_jl_competition_state` (`published`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_season` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 1,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_season_uuid` (`uuid`),
  KEY `idx_jl_season_dates` (`start_date`, `end_date`),
  KEY `idx_jl_season_state` (`published`, `ordering`),
  CONSTRAINT `chk_jl_season_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `competition_id` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL,
  `sport_type_id` BIGINT UNSIGNED NOT NULL,
  `profile_version_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `external_code` VARCHAR(191) NULL DEFAULT NULL,
  `project_type` VARCHAR(100) NOT NULL,
  `timezone` VARCHAR(100) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `default_start_time` VARCHAR(5) NULL DEFAULT NULL,
  `current_round_mode` VARCHAR(30) NOT NULL DEFAULT 'manual',
  `auto_advance_seconds` INT UNSIGNED NULL DEFAULT NULL,
  `lifecycle_state` VARCHAR(30) NOT NULL DEFAULT 'draft',
  `description` TEXT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `metadata_json` LONGTEXT NULL,
  `published` TINYINT NOT NULL DEFAULT 0,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `checked_out` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checked_out_time` DATETIME NULL DEFAULT NULL,
  `asset_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_uuid` (`uuid`),
  KEY `idx_jl_project_competition` (`competition_id`),
  KEY `idx_jl_project_season` (`season_id`),
  KEY `idx_jl_project_profile` (`profile_version_id`),
  KEY `idx_jl_project_state` (`published`, `lifecycle_state`, `ordering`),
  KEY `idx_jl_project_schedule` (`start_date`, `end_date`),
  CONSTRAINT `fk_jl_project_competition` FOREIGN KEY (`competition_id`) REFERENCES `#__joomleague_competition` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_season` FOREIGN KEY (`season_id`) REFERENCES `#__joomleague_season` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_jl_project_sport_binding` FOREIGN KEY (`sport_type_id`, `profile_version_id`) REFERENCES `#__joomleague_sport_type` (`id`, `profile_version_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_jl_project_dates` CHECK (`end_date` IS NULL OR `start_date` IS NULL OR `end_date` >= `start_date`),
  CONSTRAINT `chk_jl_project_auto_advance` CHECK (`auto_advance_seconds` IS NULL OR `auto_advance_seconds` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_rule_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `overrides_json` LONGTEXT NOT NULL,
  `overrides_checksum` CHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_rule_config` (`project_id`),
  CONSTRAINT `fk_jl_project_rule_config_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__joomleague_project_template_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `template_code` VARCHAR(100) NOT NULL,
  `schema_version` VARCHAR(50) NOT NULL,
  `params_json` LONGTEXT NOT NULL,
  `params_checksum` CHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL DEFAULT NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jl_project_template_config` (`project_id`, `template_code`),
  KEY `idx_jl_project_template_code` (`template_code`),
  CONSTRAINT `fk_jl_project_template_project` FOREIGN KEY (`project_id`) REFERENCES `#__joomleague_project` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
