CREATE TABLE IF NOT EXISTS "#__joomleague_standing_snapshot" (
  "id" BIGSERIAL PRIMARY KEY, "uuid" CHAR(36) NOT NULL, "project_id" BIGINT NOT NULL, "stage_id" BIGINT NULL, "stage_key" BIGINT NOT NULL DEFAULT 0, "scope_code" VARCHAR(100) NOT NULL, "standings_type" VARCHAR(100) NOT NULL, "profile_version_id" BIGINT NOT NULL, "profile_checksum" CHAR(64) NOT NULL, "input_checksum" CHAR(64) NOT NULL, "contract_json" TEXT NOT NULL, "row_count" INTEGER NOT NULL DEFAULT 0, "generated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "generated_by" BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT "uq_jl_standing_snapshot_uuid" UNIQUE ("uuid"), CONSTRAINT "uq_jl_standing_snapshot_input" UNIQUE ("project_id", "stage_key", "scope_code", "input_checksum"), CONSTRAINT "uq_jl_standing_snapshot_owner" UNIQUE ("id", "project_id"), CONSTRAINT "fk_jl_standing_snapshot_project" FOREIGN KEY ("project_id") REFERENCES "#__joomleague_project" ("id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_snapshot_stage" FOREIGN KEY ("stage_id", "project_id") REFERENCES "#__joomleague_project_stage" ("id", "project_id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_snapshot_profile" FOREIGN KEY ("profile_version_id") REFERENCES "#__joomleague_sport_profile_version" ("id") ON DELETE RESTRICT, CONSTRAINT "chk_jl_standing_snapshot_stage" CHECK (("stage_id" IS NULL AND "stage_key" = 0) OR ("stage_id" IS NOT NULL AND "stage_key" = "stage_id")), CONSTRAINT "chk_jl_standing_snapshot_rows" CHECK ("row_count" >= 0)
);
CREATE INDEX "idx_jl_standing_snapshot_stage" ON "#__joomleague_standing_snapshot" ("stage_id", "generated_at") /** CAN FAIL **/;
CREATE TABLE IF NOT EXISTS "#__joomleague_standing_snapshot_row" (
  "id" BIGSERIAL PRIMARY KEY, "snapshot_id" BIGINT NOT NULL, "project_entry_id" BIGINT NULL, "entry_id_snapshot" BIGINT NOT NULL, "entry_name_snapshot" VARCHAR(255) NOT NULL, "rank_number" INTEGER NOT NULL, "sequence_number" INTEGER NOT NULL, "metrics_json" TEXT NOT NULL,
  CONSTRAINT "uq_jl_standing_row_entry" UNIQUE ("snapshot_id", "entry_id_snapshot"), CONSTRAINT "fk_jl_standing_row_snapshot" FOREIGN KEY ("snapshot_id") REFERENCES "#__joomleague_standing_snapshot" ("id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_row_entry" FOREIGN KEY ("project_entry_id") REFERENCES "#__joomleague_project_entry" ("id") ON DELETE SET NULL, CONSTRAINT "chk_jl_standing_row_rank" CHECK ("rank_number" > 0 AND "sequence_number" > 0)
);
CREATE INDEX "idx_jl_standing_row_order" ON "#__joomleague_standing_snapshot_row" ("snapshot_id", "sequence_number") /** CAN FAIL **/;
CREATE INDEX "idx_jl_standing_row_entry" ON "#__joomleague_standing_snapshot_row" ("project_entry_id") /** CAN FAIL **/;
CREATE TABLE IF NOT EXISTS "#__joomleague_standing_current" (
  "project_id" BIGINT NOT NULL, "stage_key" BIGINT NOT NULL DEFAULT 0, "scope_code" VARCHAR(100) NOT NULL, "snapshot_id" BIGINT NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_by" BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("project_id", "stage_key", "scope_code"), CONSTRAINT "uq_jl_standing_current_snapshot" UNIQUE ("snapshot_id"), CONSTRAINT "fk_jl_standing_current_project" FOREIGN KEY ("project_id") REFERENCES "#__joomleague_project" ("id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_current_snapshot" FOREIGN KEY ("snapshot_id", "project_id") REFERENCES "#__joomleague_standing_snapshot" ("id", "project_id") ON DELETE CASCADE
);
