CREATE TABLE IF NOT EXISTS "#__joomleague_standing_adjustment" (
  "id" BIGSERIAL PRIMARY KEY, "uuid" CHAR(36) NOT NULL, "project_id" BIGINT NOT NULL, "stage_id" BIGINT NULL, "stage_key" BIGINT NOT NULL DEFAULT 0,
  "project_entry_id" BIGINT NOT NULL, "scope_code" VARCHAR(100) NOT NULL DEFAULT 'all', "metric_code" VARCHAR(100) NOT NULL, "adjustment_value" NUMERIC(30,9) NOT NULL, "reason" VARCHAR(500) NOT NULL, "effective_date" DATE NULL,
  "published" SMALLINT NOT NULL DEFAULT 1, "ordering" INTEGER NOT NULL DEFAULT 0, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_by" BIGINT NOT NULL DEFAULT 0, "modified" TIMESTAMP WITHOUT TIME ZONE NULL, "modified_by" BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT "uq_jl_standing_adjustment_uuid" UNIQUE ("uuid"), CONSTRAINT "fk_jl_standing_adjustment_project" FOREIGN KEY ("project_id") REFERENCES "#__joomleague_project" ("id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_adjustment_stage" FOREIGN KEY ("stage_id", "project_id") REFERENCES "#__joomleague_project_stage" ("id", "project_id") ON DELETE CASCADE, CONSTRAINT "fk_jl_standing_adjustment_entry" FOREIGN KEY ("project_entry_id", "project_id") REFERENCES "#__joomleague_project_entry" ("id", "project_id") ON DELETE CASCADE,
  CONSTRAINT "chk_jl_standing_adjustment_stage" CHECK (("stage_id" IS NULL AND "stage_key" = 0) OR ("stage_id" IS NOT NULL AND "stage_key" = "stage_id")), CONSTRAINT "chk_jl_standing_adjustment_scope" CHECK ("scope_code" ~ '^[a-z][a-z0-9_]*$'), CONSTRAINT "chk_jl_standing_adjustment_metric" CHECK ("metric_code" ~ '^[a-z][a-z0-9_]*$'), CONSTRAINT "chk_jl_standing_adjustment_value" CHECK ("adjustment_value" <> 0), CONSTRAINT "chk_jl_standing_adjustment_published" CHECK ("published" IN (0,1))
);
CREATE INDEX "idx_jl_standing_adjustment_context" ON "#__joomleague_standing_adjustment" ("project_id", "stage_key", "scope_code", "published", "ordering") /** CAN FAIL **/;
CREATE INDEX "idx_jl_standing_adjustment_entry" ON "#__joomleague_standing_adjustment" ("project_entry_id") /** CAN FAIL **/;
