CREATE TABLE IF NOT EXISTS "#__joomleague_stage_transition" (
  "id" BIGSERIAL PRIMARY KEY, "uuid" CHAR(36) NOT NULL, "project_id" BIGINT NOT NULL, "source_stage_id" BIGINT NOT NULL, "target_stage_id" BIGINT NOT NULL,
  "code" VARCHAR(100) NOT NULL, "name" VARCHAR(255) NOT NULL, "selector_type" VARCHAR(100) NOT NULL, "selector_config_json" TEXT NULL, "carry_over_mode" VARCHAR(100) NOT NULL DEFAULT 'none', "target_seed_start" INTEGER NULL,
  "published" SMALLINT NOT NULL DEFAULT 1, "ordering" INTEGER NOT NULL DEFAULT 0, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_by" BIGINT NOT NULL DEFAULT 0, "modified" TIMESTAMP WITHOUT TIME ZONE NULL, "modified_by" BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT "uq_jl_stage_transition_uuid" UNIQUE ("uuid"), CONSTRAINT "uq_jl_stage_transition_code" UNIQUE ("project_id", "code"), CONSTRAINT "fk_jl_stage_transition_project" FOREIGN KEY ("project_id") REFERENCES "#__joomleague_project" ("id") ON DELETE CASCADE, CONSTRAINT "fk_jl_stage_transition_source" FOREIGN KEY ("source_stage_id", "project_id") REFERENCES "#__joomleague_project_stage" ("id", "project_id") ON DELETE CASCADE, CONSTRAINT "fk_jl_stage_transition_target" FOREIGN KEY ("target_stage_id", "project_id") REFERENCES "#__joomleague_project_stage" ("id", "project_id") ON DELETE CASCADE,
  CONSTRAINT "chk_jl_stage_transition_distinct" CHECK ("source_stage_id" <> "target_stage_id"), CONSTRAINT "chk_jl_stage_transition_selector" CHECK ("selector_type" ~ '^[a-z][a-z0-9_]*$'), CONSTRAINT "chk_jl_stage_transition_carry" CHECK ("carry_over_mode" ~ '^[a-z][a-z0-9_]*$'), CONSTRAINT "chk_jl_stage_transition_seed" CHECK ("target_seed_start" IS NULL OR "target_seed_start" > 0), CONSTRAINT "chk_jl_stage_transition_published" CHECK ("published" IN (0,1))
);
CREATE INDEX "idx_jl_stage_transition_source" ON "#__joomleague_stage_transition" ("source_stage_id", "project_id", "published", "ordering") /** CAN FAIL **/;
CREATE INDEX "idx_jl_stage_transition_target" ON "#__joomleague_stage_transition" ("target_stage_id", "project_id") /** CAN FAIL **/;
