<?php
/**
 * @package     JoomLeague
 * @copyright   Copyright (C) 2026 Ondřej Klučka (https://klucon.cz). All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

declare(strict_types=1);
\defined('_JEXEC') or die;
use Joomla\CMS\Component\ComponentHelper; use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Language\Text; use Joomla\CMS\Layout\LayoutHelper; use Joomla\CMS\Router\Route; use Joomla\CMS\Uri\Uri;
$this->getDocument()->getWebAssetManager()->useScript('multiselect');$user=$this->getCurrentUser();$order=$this->escape($this->state->get('list.ordering'));$direction=$this->escape($this->state->get('list.direction'));
$types=['SIMPLE_LEAGUE'=>'COM_JOOMLEAGUE_PROJECT_TYPE_LEAGUE','DIVISIONS_LEAGUE'=>'COM_JOOMLEAGUE_PROJECT_TYPE_DIVISIONS','TOURNAMENT_MODE'=>'COM_JOOMLEAGUE_PROJECT_TYPE_TOURNAMENT','FRIENDLY_MATCHES'=>'COM_JOOMLEAGUE_PROJECT_TYPE_FRIENDLY','RUNNING_RACE'=>'COM_JOOMLEAGUE_PROJECT_TYPE_RUNNING_RACE'];
?>
<form action="<?php echo Route::_('index.php?option=com_joomleague&view=projects'); ?>" method="post" name="adminForm" id="adminForm"><div id="j-main-container" class="j-main-container">
<?php echo LayoutHelper::render('joomla.searchtools.default',['view'=>$this]); ?>
<?php if(!$this->items): ?><div class="alert alert-info"><?php echo Text::_('JGLOBAL_NO_MATCHING_RESULTS'); ?></div><?php else: ?>
<table class="table"><caption class="visually-hidden"><?php echo Text::_('COM_JOOMLEAGUE_PROJECTS_TITLE'); ?></caption><thead><tr><td class="w-1 text-center"><?php echo HTMLHelper::_('grid.checkall'); ?></td><th class="w-1 text-center"><span class="icon-edit" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('JACTION_EDIT'); ?></span></th><th class="w-5"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_IMAGE'); ?></th><th><?php echo HTMLHelper::_('searchtools.sort','COM_JOOMLEAGUE_FIELD_NAME','a.name',$direction,$order); ?></th><th><?php echo HTMLHelper::_('searchtools.sort','COM_JOOMLEAGUE_PROJECT_FIELD_LEAGUE','l.name',$direction,$order); ?></th><th><?php echo HTMLHelper::_('searchtools.sort','COM_JOOMLEAGUE_PROJECT_FIELD_SEASON','s.name',$direction,$order); ?></th><th><?php echo HTMLHelper::_('searchtools.sort','COM_JOOMLEAGUE_FIELD_SPORT','st.name',$direction,$order); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_PROJECT_FIELD_TYPE'); ?></th><th class="text-center"><?php echo Text::_('COM_JOOMLEAGUE_PROJECT_ROUNDS'); ?></th><th class="text-center"><?php echo Text::_('COM_JOOMLEAGUE_PROJECT_MATCHES'); ?></th><th class="w-1 text-center"><?php echo HTMLHelper::_('searchtools.sort','JSTATUS','a.published',$direction,$order); ?></th><th class="w-3"><?php echo HTMLHelper::_('searchtools.sort','JGRID_HEADING_ID','a.id',$direction,$order); ?></th></tr></thead><tbody>
<?php foreach($this->items as $i=>$item): $canEdit=$user->authorise('core.edit','com_joomleague');$canChange=$user->authorise('core.edit.state','com_joomleague');
$projectPicture=trim((string)($item->picture??''))!==''?(string)$item->picture:(string)ComponentHelper::getParams('com_joomleague')->get('placeholder_project_picture','');
$projectImage=HTMLHelper::cleanImageURL($projectPicture);$projectImageSrc=$projectImage->url===''?'':Uri::root(true).'/'.ltrim($projectImage->url,'/');
?>
<tr><td class="text-center"><?php echo HTMLHelper::_('grid.id',$i,$item->id); ?></td><td class="text-center"><?php if($canEdit): ?><a href="<?php echo Route::_('index.php?option=com_joomleague&task=project.edit&id='.(int)$item->id); ?>" title="<?php echo Text::_('JACTION_EDIT'); ?>"><span class="icon-edit" aria-hidden="true"></span></a><?php endif; ?></td><td><?php if($projectImageSrc!==''): ?><img src="<?php echo $this->escape($projectImageSrc); ?>" alt="" width="32" height="32" loading="lazy" class="rounded object-fit-contain"><?php else: ?><span class="icon-image text-muted" aria-hidden="true"></span><?php endif; ?></td><th scope="row"><a href="<?php echo Route::_('index.php?option=com_joomleague&view=projectpanel&project_id='.(int)$item->id); ?>"><?php echo $this->escape($item->name); ?></a></th><td><?php echo $this->escape($item->league); ?></td><td><?php echo $this->escape($item->season); ?></td><td><?php echo $this->escape(Text::_($item->sport)); ?></td><td><?php echo Text::_($types[$item->project_type]??'COM_JOOMLEAGUE_PROJECT_TYPE_LEAGUE'); ?></td><td class="text-center"><a href="<?php echo Route::_('index.php?option=com_joomleague&view=rounds&project_id='.(int)$item->id); ?>"><?php echo (int)$item->round_count; ?></a></td><td class="text-center"><a href="<?php echo Route::_('index.php?option=com_joomleague&view=matches&project_id='.(int)$item->id.'&round_id='.(int)$item->latest_round_id); ?>" title="<?php echo Text::_('COM_JOOMLEAGUE_PROJECT_MATCHES'); ?>"><span class="icon-calendar" aria-hidden="true"></span></a></td><td class="text-center"><?php echo HTMLHelper::_('jgrid.published',$item->published,$i,'projects.',$canChange); ?></td><td><?php echo (int)$item->id; ?></td></tr>
<?php endforeach; ?></tbody></table><?php echo $this->pagination->getListFooter(); ?><?php endif; ?><?php echo $this->filterForm->renderControlFields(); ?></div></form>
