<?php

defined('_JEXEC') or die;

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;

$matchId = (int) $this->match->id;
$participantNames = [];
foreach ($this->participants as $participant) $participantNames[(int) $participant->id] = (string) $participant->display_name;
$phaseDefinitions = [];
foreach ($this->profile['match']['score']['segment_types'] ?? [] as $segment) if (is_array($segment) && is_string($segment['code'] ?? null)) $phaseDefinitions[$segment['code']] = (string) ($segment['name_key'] ?? $segment['code']);
?>
<form action="<?php echo Route::_('index.php?option=com_joomleague&view=matchevents&match_id=' . $matchId); ?>" method="post" name="adminForm" id="adminForm">
	<div class="container-fluid">
		<div class="alert alert-info" role="status"><strong><?php echo $this->escape($this->project->name); ?></strong><span class="mx-2">/</span><?php echo $this->escape($this->match->match_number ?: Text::_('COM_JOOMLEAGUE_MATCH_UNNUMBERED')); ?><div><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_DESC'); ?></div></div>
		<?php if ($this->canEdit) : ?>
		<fieldset class="options-form mb-4"><legend><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_ADD'); ?></legend>
			<div class="row g-3">
				<div class="col-lg-4"><label class="form-label" for="match-event-code"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_EVENT_TYPE_LABEL'); ?></label><select class="form-select" id="match-event-code" name="event_code" required><option value=""><?php echo Text::_('COM_JOOMLEAGUE_OPTION_SELECT_EVENT'); ?></option><?php foreach ($this->eventDefinitions as $definition) : ?><option value="<?php echo $this->escape($definition['code']); ?>"><?php echo Text::_($definition['name_key']); ?></option><?php endforeach; ?></select><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_EVENT_DESC'); ?></div></div>
				<div class="col-lg-4"><label class="form-label" for="match-event-participant"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_PARTICIPANT_LABEL'); ?></label><select class="form-select" id="match-event-participant" name="match_participant_id"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($this->participants as $participant) : ?><option value="<?php echo (int) $participant->id; ?>"><?php echo $this->escape($participant->display_name); ?></option><?php endforeach; ?></select><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_PARTICIPANT_DESC'); ?></div></div>
				<div class="col-lg-4"><label class="form-label" for="match-event-official"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_ACTOR_LABEL'); ?></label><select class="form-select" id="match-event-official" name="source_match_actor_role_id"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($this->officials as $official) : ?><option value="<?php echo (int) $official->id; ?>"><?php echo $this->escape($official->display_name_snapshot); ?></option><?php endforeach; ?></select><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_ACTOR_DESC'); ?></div></div>
				<div class="col-lg-6"><label class="form-label" for="match-event-primary"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_PRIMARY_PERSON'); ?></label><select class="form-select" id="match-event-primary" name="primary_lineup_member_id"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($this->lineup as $member) : ?><option value="<?php echo (int) $member->id; ?>"><?php echo $this->escape(($participantNames[(int) $member->match_participant_id] ?? '') . ' - ' . $member->display_name); ?></option><?php endforeach; ?></select><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_PRIMARY_PERSON_DESC'); ?></div></div>
				<div class="col-lg-6"><label class="form-label" for="match-event-secondary"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_SECOND_PERSON'); ?></label><select class="form-select" id="match-event-secondary" name="secondary_lineup_member_id"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($this->lineup as $member) : ?><option value="<?php echo (int) $member->id; ?>"><?php echo $this->escape(($participantNames[(int) $member->match_participant_id] ?? '') . ' - ' . $member->display_name); ?></option><?php endforeach; ?></select><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_SECOND_PERSON_DESC'); ?></div></div>
				<div class="col-md-3"><label class="form-label" for="match-event-phase"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_PHASE_LABEL'); ?></label><select class="form-select" id="match-event-phase" name="phase_code"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($phaseDefinitions as $code => $nameKey) : ?><option value="<?php echo $this->escape($code); ?>"><?php echo Text::_($nameKey); ?></option><?php endforeach; ?></select></div>
				<div class="col-md-3"><label class="form-label" for="match-event-phase-sequence"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_PHASE_SEQUENCE_LABEL'); ?></label><input class="form-control" type="number" min="1" id="match-event-phase-sequence" name="phase_sequence"></div>
				<div class="col-md-3"><label class="form-label" for="match-event-clock"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_CLOCK_VALUE_LABEL'); ?></label><input class="form-control" inputmode="decimal" id="match-event-clock" name="clock_value"></div>
				<div class="col-md-3"><label class="form-label" for="match-event-clock-unit"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_CLOCK_UNIT_LABEL'); ?></label><input class="form-control" id="match-event-clock-unit" name="clock_unit" placeholder="<?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_CLOCK_UNIT_PLACEHOLDER'); ?>"></div>
				<div class="col-lg-4"><label class="form-label" for="match-event-segment"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_SCORE_SEGMENT_LABEL'); ?></label><select class="form-select" id="match-event-segment" name="score_segment_id"><option value=""><?php echo Text::_('JNONE'); ?></option><?php foreach ($this->segments as $segment) : ?><option value="<?php echo (int) $segment->id; ?>"><?php echo Text::_($phaseDefinitions[$segment->level_code] ?? $segment->level_code); ?> <?php echo (int) $segment->sequence_number; ?></option><?php endforeach; ?></select></div>
				<div class="col-lg-4"><label class="form-label" for="match-event-occurred"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_OCCURRED_AT_LABEL'); ?></label><input class="form-control" type="datetime-local" id="match-event-occurred" name="occurred_at"><div class="form-text"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_OCCURRED_AT_DESC'); ?></div></div>
				<div class="col-lg-4"><label class="form-label" for="match-event-value"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_NUMERIC_VALUE_LABEL'); ?></label><input class="form-control" inputmode="decimal" id="match-event-value" name="numeric_value"></div>
				<div class="col-lg-6"><label class="form-label" for="match-event-text"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_TEXT_VALUE_LABEL'); ?></label><input class="form-control" id="match-event-text" name="text_value" maxlength="255"></div>
				<div class="col-lg-6"><label class="form-label" for="match-event-notes"><?php echo Text::_('COM_JOOMLEAGUE_FIELD_NOTES_LABEL'); ?></label><textarea class="form-control" id="match-event-notes" name="notes" rows="2"></textarea></div>
			</div>
			<button class="btn btn-success mt-3" type="submit" name="task" value="matchevents.add"><span class="icon-plus" aria-hidden="true"></span> <?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_ADD'); ?></button>
		</fieldset>
		<?php endif; ?>
		<h2 class="h4"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_TIMELINE'); ?></h2>
		<div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th class="w-1"><span class="visually-hidden"><?php echo Text::_('JGLOBAL_SELECTION'); ?></span></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_SEQUENCE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_EVENT_TYPE_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_PARTICIPANT_LABEL'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_SUBJECT'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_TIME'); ?></th><th><?php echo Text::_('COM_JOOMLEAGUE_FIELD_VALUE_LABEL'); ?></th></tr></thead><tbody>
		<?php foreach ($this->events as $event) : ?><tr><td><input class="form-check-input" type="checkbox" name="cid[]" value="<?php echo (int) $event->id; ?>" aria-label="<?php echo Text::_('JGLOBAL_SELECTION'); ?>"></td><td><?php echo (int) $event->sequence_number; ?></td><th scope="row"><?php echo Text::_($event->event_name_key); ?></th><td><?php echo $this->escape($participantNames[(int) $event->match_participant_id] ?? Text::_('JNONE')); ?></td><td><?php echo $this->escape($event->primary_name_snapshot ?: ($event->actor_name_snapshot ?: Text::_('JNONE'))); ?><?php if ($event->secondary_name_snapshot) : ?><div class="small text-body-secondary"><?php echo $this->escape($event->secondary_name_snapshot); ?></div><?php endif; ?></td><td><?php echo $this->escape($event->phase_code ?: Text::_('JNONE')); ?><?php if ($event->phase_sequence) : ?> <?php echo (int) $event->phase_sequence; ?><?php endif; ?><?php if ($event->clock_value !== null) : ?><div class="small text-body-secondary"><?php echo $this->escape($event->clock_value . ' ' . $event->clock_unit); ?></div><?php endif; ?></td><td><?php echo $this->escape($event->numeric_value ?? ($event->text_value ?? Text::_('JNONE'))); ?></td></tr><?php endforeach; ?>
		<?php if ($this->events === []) : ?><tr><td colspan="7"><div class="alert alert-light mb-0"><?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_EMPTY'); ?></div></td></tr><?php endif; ?>
		</tbody></table></div>
		<?php if ($this->canEdit && $this->events !== []) : ?><button class="btn btn-danger" type="submit" name="task" value="matchevents.remove"><span class="icon-minus" aria-hidden="true"></span> <?php echo Text::_('COM_JOOMLEAGUE_MATCHEVENTS_REMOVE'); ?></button><?php endif; ?>
	</div>
	<input type="hidden" name="task" value=""><input type="hidden" name="match_id" value="<?php echo $matchId; ?>"><?php echo HTMLHelper::_('form.token'); ?>
</form>
