<?php
declare(strict_types=1);
use Joomla\CMS\Language\Text;use Joomla\CMS\Router\Route;
defined('_JEXEC') or die;$data=$this->comparison;$escape=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<div class="com-joomleague-comparison">
<?php if(isset($data['error'])):?><div class="alert alert-warning"><?php echo Text::_($data['error']);?></div><?php else:?>
<header class="border-bottom pb-3 mb-4"><h1 class="mb-1"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_VIEW_TITLE');?></h1><div class="text-body-secondary"><?php echo $escape($data['project']->name);?></div></header>
<?php if(count($data['entries'])<2):?><div class="alert alert-info"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_NOT_ENOUGH_ENTRIES');?></div><?php else:?>
<form action="<?php echo Route::_('index.php');?>" method="get" class="row g-3 align-items-end mb-4"><input type="hidden" name="option" value="com_joomleague"><input type="hidden" name="view" value="comparison"><input type="hidden" name="project_id" value="<?php echo(int)$data['project']->id;?>">
<?php foreach(['first_id'=>'COM_JOOMLEAGUE_COMPARISON_FIRST','second_id'=>'COM_JOOMLEAGUE_COMPARISON_SECOND']as$name=>$label):?><div class="col-12 col-md-5"><label class="form-label" for="comparison-<?php echo$name;?>"><?php echo Text::_($label);?></label><select class="form-select" id="comparison-<?php echo$name;?>" name="<?php echo$name;?>" required><option value=""><?php echo Text::_('JSELECT');?></option><?php foreach($data['entries']as$entry):?><option value="<?php echo(int)$entry->id;?>"<?php echo $data['selected']&&((int)$data['selected'][$name==='first_id'?0:1]->id===(int)$entry->id)?' selected':'';?>><?php echo$escape($entry->display_name);?></option><?php endforeach;?></select></div><?php endforeach;?><div class="col-12 col-md-2"><button class="btn btn-primary w-100" type="submit"><span class="icon-shuffle" aria-hidden="true"></span> <?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_COMPARE');?></button></div></form>
<?php if($data['selected']):$first=$data['selected'][0];$second=$data['selected'][1];?>
<div class="row row-cols-2 row-cols-lg-4 g-3 mb-4"><div class="col"><div class="border rounded p-3 h-100 text-center"><div class="fs-3 fw-semibold"><?php echo count($data['events']);?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_SHARED_EVENTS');?></div></div></div><div class="col"><div class="border rounded p-3 h-100 text-center"><div class="fs-3 fw-semibold"><?php echo(int)$data['summary']['first'];?></div><div class="text-body-secondary"><?php echo$escape($first->display_name);?></div></div></div><div class="col"><div class="border rounded p-3 h-100 text-center"><div class="fs-3 fw-semibold"><?php echo(int)$data['summary']['draw'];?></div><div class="text-body-secondary"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_EQUAL');?></div></div></div><div class="col"><div class="border rounded p-3 h-100 text-center"><div class="fs-3 fw-semibold"><?php echo(int)$data['summary']['second'];?></div><div class="text-body-secondary"><?php echo$escape($second->display_name);?></div></div></div></div>
<?php if($data['events']===[]):?><div class="alert alert-info"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_EMPTY');?></div><?php else:?><div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th scope="col"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_EVENT');?></th><th scope="col"><?php echo Text::_('COM_JOOMLEAGUE_COMPARISON_DATE');?></th><th scope="col" class="text-end"><?php echo$escape($first->display_name);?></th><th scope="col" class="text-end"><?php echo$escape($second->display_name);?></th></tr></thead><tbody><?php foreach($data['events']as$row):?><tr><th scope="row"><a href="<?php echo Route::_('index.php?option=com_joomleague&view=eventreport&event_id='.(int)$row['event']->id);?>"><?php echo$escape($row['event']->round_name);?></a><div class="small text-body-secondary"><?php echo$escape($row['event']->stage_name);?></div></th><td><?php echo$row['event']->scheduled_start?$escape((string)$row['event']->scheduled_start):Text::_('JNONE');?></td><td class="text-end fw-semibold"><?php echo$escape($row['first']['display']??'—');?></td><td class="text-end fw-semibold"><?php echo$escape($row['second']['display']??'—');?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;endif;endif;?>
</div>
